export const STRAVA_BASE_URL = 'https://www.strava.com'
export const LOCAL_STORAGE_TOKEN_KEY = 'performanceGraphs-token-data'
export const LOCAL_STORAGE_SETTINGS_KEY = 'performanceGraphs-settings'
export const LOCAL_STORAGE_IS_DEMO_MODE = 'performanceGraphs-demo-mode'
export const LOCAL_STORAGE_ADV_SETTINGS = 'performanceGraphs-advSettings'
export const LOCAL_STORAGE_CLICK_POINT_REMOVE = 'performanceGraphs-clickRm'
export const LOCAL_STORAGE_ACTIVITIES = 'performanceGraphs-activities'