import { Activity, Athlete } from './types'

export const sampleAthlete: Athlete = {
    "id": 123,
    "username": "23Jordanator1963",
    "resource_state": 2,
    "firstname": "Michael",
    "lastname": "Jordan",
    "bio": "Just an average guy, trying to make a name for myself!",
    "city": "Wilmington",
    "state": "North Carolina",
    "country": "United States",
    "sex": "M",
    "premium": false,
    "summit": false,
    "created_at": "2024-05-13T01:12:45Z",
    "updated_at": "2024-10-21T04:06:10Z",
    "badge_type_id": 0,
    "weight": "216",
    "profile_medium": "https://www.basketball-reference.com/players/j/jordami01.html",
    "profile": "https://www.basketball-reference.com/players/j/jordami01.html",
    "friend": null,
    "follower": null
}

export const sampleActivities: Activity[] = [
    {
        "resource_state": 2,
        "average_watts": 117.2,
        "athlete": {
            "id": 1,
            "resource_state": 1
        },
        "name": "First Bike Ride!",
        "distance": 28784.9,
        "moving_time": 3939,
        "elapsed_time": 4167,
        "total_elevation_gain": 108,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12369838444,
        "start_date": "2024-09-09T20:59:32Z",
        "start_date_local": "2024-09-09T15:59:32Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 17,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12369838444",
            "summary_polyline": "ahoqGloixPm@iAKu@l@a@u@cBqAwBmC_Dq@_Bo@w@_@sAyAaBg@}AiA}@u@}@wB{Du@g@Gg@iCgEgBaCgAQq@mA]O_@wA_@WBSUc@iAGHSEk@mBeFaBmCw@gCqBiCNATj@Km@OIVr@f@{@uAk@TkBl@_BbFmH|AkBnAiAXCrBaH~@gA|As@v@sBrAkBdDkK\\_@ICx@QHo@IQTUUa@FWSUBm@?D\\]?a@Y?Dk@dFeVLkCGiCoC|P_@gAj@mDFqBi@}DC_AD_Bp@sFY}C\\{@TqFhAoCxDuEbA}ArAs@z@mBPKfCWnBuAxAe@|FBjCm@bCcArCsBlCwD|@yBlCcJpA{M`B_LPmDhC}M|A{DvAcCjBqBRo@fA}@jAq@zJwIJ[DJ|HiKRCn@yAbHgHbFkInD_EhK{V~CeCFh@iBbBxBrFvCjLjApKXzGQdXiArr@?|DHdCHdAbAjCpC~Bq@rBeAbBrAnGnA`EBbAn@\\FZXvDCfQnEtLjAlFI`@XzDGp@FtNSpBAxALb@?fCPdCArESfKDdCUlB?pCZxC?tAM~Eg@?TxALrEZAQTAz@HpC@jBI~COz@LxBQfF?pBX~BDrCAjVQpBHRRzFAlFXt@Ct@c@`AN~JSfIPpGOrFNbAMhGFzHOxCEbIPlDDrIU`HHjBKBGpAZdFOtCCtAFtKIg@Xp@HjQI`G]~HBlDOvB_AeAQ?]j@[rF_ClUo@bEk@dA}APeCWkJ|AsEAgBt@wAPq@c@i@oADmEYqAu@s@yBFaBu@{@eBC{Bx@eB|BkBvCqCrDYh@]Xk@HwA_@_BmB}BmJuCsBQeDP}EjBcBPkBIg@m@Mu@HgBv@{ApJqJ|@Op@PlLjJfCdAxBVpAq@Xm@|@oEp@qB`@_@jBa@|@PfFbEdCrAfCvDfCrCpA~Dt@s@j@AnDbAj@b@|DSTTHx@dCh@rLiEbIiEfBu@|Bi@tBZvGM|Mp@zGrBvChCr@XjA~BT|AhCvFpBvKJrG]nCu@tDmAdBoArD@fAYrCd@|DOdEVxEMvB_ArDaA~@aBGcHoCuCOiCd@wAtAsEh@qFIqIaAuDcAcEcCwIcJeEeCkB_C]mAkAqFAqC{AeG]kDs@wCP_Ct@mBHqAt@eDpAkEvB}EX_@HbAtATTMYYgACSsAaEDqAsAcAYyAKo@bA|@|@ROEkANeA\\}PBc[K_KHiNQsGL}GC}XSIA[YBCYTe@M[wDL_AQi@^UU_I?YbB@jJUP_AGtAEh@P\\CCO",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.975530626252294,
            -93.27878661453724
        ],
        "end_latlng": [
            44.95346685871482,
            -93.28788659535348
        ],
        "average_speed": 7.308,
        "max_speed": 22.456,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 267.9,
        "elev_low": 224.4,
        "upload_id": 13188260849,
        "upload_id_str": "13188260849",
        "external_id": "stripped_72A3379C-E1AB-4E44-B050-48F055EB7429-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 4,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 160.8,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Night Ride",
        "distance": 10424.2,
        "moving_time": 1473,
        "elapsed_time": 1487,
        "total_elevation_gain": 37.2,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12370967770,
        "start_date": "2024-09-10T01:13:08Z",
        "start_date_local": "2024-09-09T20:13:08Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 4,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12370967770",
            "summary_polyline": "{}nqG`gjxPITOu@OKQo@Io@R_@[aA?Wc@y@k@eCmAyCu@_CKQ{@{CiAiCoAgBu@}A{@qAGO@g@i@Qg@o@k@iAUMKa@s@a@I]aAkBw@mAyAgBSk@WWEa@yBcDa@w@Su@m@i@oAeBe@e@[o@k@m@yAkCAUKU{@cA_AqAw@uAmBaCWm@TEMa@MAm@iAc@i@ICE_@YWa@s@LGXl@BIOc@MCLd@JF?ID?\\s@m@Oa@_@GB[l@_@XkAFk@\\mCvEe@CwA^}@d@g@BgAn@QBgAx@{AlC@\\GT@l@OXe@j@wBbBw@bAs@~Bm@`D{@bD@TNt@p@jB?p@Jd@QrAc@l@eA\\iBFw@P_Ar@k@z@g@b@IVOPmBMWBcFvBiGjB_En@iD^mBLcBF_@Jo@|@OFqAG]WCa@GOi@QgAOIFCNNT`@?j@P^fAVRELPJCHNQ@Ll@IFIp@Qr@y@JCpG_@bGi@`DoArAKv@WbAg@`Bi@`B}@lAKRDt@sA|@gAhAaAfAJn@`@bA]\\W`@u@V_AHm@?aBMk@m@}ASw@Fq@h@wA`@e@Le@Du@N}@b@qAVc@B[HQnAcA\\@p@s@Li@D_ALy@`@_@vA}B~BeAL@vA_@vB}@d@g@h@gAz@qAf@i@\\Un@Er@m@GPV}@RuAXy@~AwBzAcCvAiBlAwA\\Ml@i@|@aC`AeDhAyAXEp@q@`@w@h@]Vs@BY\\]TNN\\xBdBZf@DRJFVETNG?@HJAPIRc@RRBj@XGZb@|An@^RlApAFZf@ZX^^bA`@ZjBbCz@d@`@f@p@LhChBE@Lb@REHFhAfArAfB@HGVOXa@j@M`@KAGJKZUr@E`@Ub@S~@Gt@[\\eAhEIHc@xAKB]x@q@lDOZ_@HWQGHg@RNGD\\Gb@GBG`@H]Vh@Ef@[e@SNJb@h@n@f@~@Z|@lAzA~@p@Yd@@TFPVDPPi@pGFb@VHl@j@h@v@Rf@VHLPx@Xl@b@NZhAdADLCDD?GLATOl@@Pi@|@u@nBKtAi@bBw@f@e@HyA|AuAlAPd@zAnFV\\ED@\\Tp@JMf@JHNMF?LGLDb@d@V@R?IHBBLAKDD",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.973908979445696,
            -93.28256417065859
        ],
        "end_latlng": [
            44.9741677287966,
            -93.28174249269068
        ],
        "average_speed": 7.077,
        "max_speed": 15.772,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 261.9,
        "elev_low": 245.4,
        "upload_id": 13189450738,
        "upload_id_str": "13189450738",
        "external_id": "stripped_4E31EE09-7914-4E07-937A-DB77D6A412B7-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 102.1,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "🚲Philly",
        "distance": 25763.1,
        "moving_time": 6057,
        "elapsed_time": 7241,
        "total_elevation_gain": 34.2,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12402065140,
        "start_date": "2024-09-13T17:35:02Z",
        "start_date_local": "2024-09-13T13:35:02Z",
        "timezone": "(GMT-05:00) America/New_York",
        "utc_offset": -14400,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12402065140",
            "summary_polyline": "}xzrFr}wiMhBI\\[Gc@ORRNSMz@CReAl@e@g@mAAu@Vg@rE`@~Ax@|CCn@NO?j@k@]_FfBYWo@RkAw@aAAs@o@a@SiALa@c@aBL[Su@dAsD_@g@TGPqB{AsACc@vAaA@o@^UdA_OQk@\\i@TiGVKBeFTk@O}A`@s@f@{E`@oOT]BwCTy@dAaPzIt@|@n@fFNTy@~@{@jA_@dAGVuBZD|@aHtHx@lLTn^MxG~AzHnDvThC|GxAvGb@xCq@~IsEzJ_Hb[eQtL_GhEk@`RnCvBt@xBx@pRfCa@`AFb@V{ATC`P~B|FrDbDhGbA`Fl@bLcB~YwCl\\mF`|@_@XoDWN`@hDj@KbBw@|@d@hAWfCo@jB?tCORLQd@n@rCt@zCd@zAw@pAHBZz@s@_@eELs@KKE`@FlFaDDAnA]z@FdA~ApD|BxAR|Ba@`GtBx@tDX`@mAFaFXw@e@_Am@OFMuUwC}AGSVY_ASZuAfRe@|@cHwAqCWy@p@wFuA}CA}Es@eAa@mDQW[oToB{Bk@Ge@x@sJ_PwBkGcAaAPeFaAJuFt@_JK]eXyDmCAqIaB}@pHYLoGqAPyDS_AmH_Kk@Mm@aAw@EH_A}DsFoBeBYRd@L_@i@cHiAaAPi@g@wBLmEsAgATEe@eBHiBy@w@FoMaCuEKgBi@sIo@mCc@oFyAwBHiD]aASs@~DPhCq@dCIzATXgAZaAa@o@zAKbCNL]pABtA}@bL?|@Tb@]j@LFShAf@IWDA^d@d@i@KeApB^XQ_@?z@YbARRk@x@PdD[dCT\\O|A\\Ru@fB@rBRj@e@~@WG@r@SRb@Xm@HZfA_@pCRzAa@`AY`El@x@b@OmAt@WzEUZG`COFJ|@]lDW\\Nd@_@lJWjA?Tt@ZpIrAPIEqBn@iH[c@_Ea@?uAT]Qs@n@_@AqA_@g@oCAyAcA{@HI[p@gEAqA]Cd@qAIq@t@kGCwBH]CPVCAo@`@o@MUYgCJk@SKj@q@Ie@VIDg@u@k@l@VPe@RbAY}@pACHp@x@Ph@wDWGBq@]s@p@WjCNX\\nBI`Av@`@EAkD^oAWiAZFc@cCl@|@CiC`@}ASc@e@]{AVc@{@_Ab@Re@OTgACIc@KNk@i@C^oANiBs@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            39.95551443658769,
            -75.16649876721203
        ],
        "end_latlng": [
            39.95104872621596,
            -75.16399559564888
        ],
        "average_speed": 4.253,
        "max_speed": 18.304,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 15.9,
        "elev_low": 2,
        "upload_id": 13222637964,
        "upload_id_str": "13222637964",
        "external_id": "stripped_5D73AEAC-C7AD-4D05-8ADE-7229780415FE-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 133.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Philly Saturday",
        "distance": 28408.5,
        "moving_time": 10845,
        "elapsed_time": 20164,
        "total_elevation_gain": 111,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12411105470,
        "start_date": "2024-09-14T15:53:20Z",
        "start_date_local": "2024-09-14T11:53:20Z",
        "timezone": "(GMT-05:00) America/New_York",
        "utc_offset": -14400,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12411105470",
            "summary_polyline": "q|zrFnzuiM`Hj@bFh@vHnAEx@TTZa@pMtBX[rBfAh@KNl@bCw@jCRj@x@bCC|WjE~VbD`Hb@~@cG~@i@zPnCp@r@AeAWKOn@l@o@Np@KPGq@w@UwBWAp@Uw@qAV_Cu@Y`@Hi@kEe@oD~Ra@hIAc@]JOjAAfCqArMP~@eAnDTzDcCjZg[wDqE{AsEIaCiBi@LsBeAmHG}@KFUo@dA_CoAiA`Bg@kAw@z@\\Ha@Vd@`@[jA`@^Yj@]jCI~DmJ{@sEm@iCcAiAb@Gc@iA]uH}@mDYm@l@sFs@k@nBX~Aw@pLmNsBoGdKyEpAwLzJc@k@^b@{@l@h@jAiA|Ai@tBVdD|ABc@{DrC}DfAdBc@pAr@ZnAa@jAjB}CxDcAPyBeBEiBF|BhDjAfD{E{AmB{@rAUUpBW|@xAsDfEyB}@MvC^l@Us@}An@g@YsAlBc@hC{@Hs@rA_AH}@bAs@?qA~AMl@b@TBo@xCaANVuD`@NZUPPHYc@n@aAiAzAgB|U_ArCaFf@yEY{InDiBlAuBxBc@U}EhEuGfIcNdUvM}SzGsH`FiDq@o@O{AqAqCKmBh@aARCx@pCInBbB|YF_AnC@[fATd@f@I\\`@SNbDvB`BRc@`@h@b@p@KF_@MSLj@YaANdA^_@P~@IWd@JcBTHtA`@DFm@`Af@`@U?g@Zj@TMiATb@hALq@iAXg@?H[XVk@sAf@Lj@i@aBXa@g@fCHpAi@rAYiAp@FbAWLz@OZBX}@xADe@_Bq@r@E]jDcBZd@So@rAu@Ew@Gf@p@Iz@cCVyDx@k@C}@eBs@{CpBj@cAUGy@f@AfAg@LOg@uClAwAdAl@FGp@b@t@k@~@kAUQsCT]{GnBnBlAe@hEfBtBpAIXMH}@cBwAGkCA\\gEgBqCTW`@]UZeAvf@gOno@oHpB`\\dCsAvCyJ|DeJf@q@~An@jMp@|Dig@zDur@eI}@lA_LCeDf@aEQs@XSWa@hAqIIiAJyCdBuI[]Z_BtAi@Pm@a@Mz@Ui@mBXeBg@~@l@Xy@Uh@e@e@NRPw@b@RyBgKkAGu@i@c@lAh@Be@m@E]eAd@oFeCQ_D_BwCCaB^{@}@uFmAk@d@yEg@u@iAk@XmHkAnAsVEkGuNyBq@zC",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            39.95609873905778,
            -75.15575978904963
        ],
        "end_latlng": [
            39.96444074437022,
            -75.15628441236913
        ],
        "average_speed": 2.62,
        "max_speed": 22.186,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 34.7,
        "elev_low": 4.7,
        "upload_id": 13232369823,
        "upload_id_str": "13232369823",
        "external_id": "stripped_8F91B7C4-AD68-486D-AF39-51D92FAB3E31-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 140.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Casual Ride",
        "distance": 20334,
        "moving_time": 3485,
        "elapsed_time": 5152,
        "total_elevation_gain": 45.4,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12437505588,
        "start_date": "2024-09-17T22:23:48Z",
        "start_date_local": "2024-09-17T17:23:48Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 8,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12437505588",
            "summary_polyline": "w~lqGzykxPtA`AR`@FMz@x@JXLACFPeTjABh@Tj@OTRXU~@GpOIzMAt@JdFHdFIZROQDc@XWLEJBMS?ToAHqACrBEa@NgGMuKGIg@?kCBYJMfADd@K`@LlCHTT@bATt@C\\TbAPLjLNpBKDJzA@lAKrGLJs@YGLAFi@GSJWGDFLOhACrIFPCnHJpAOfDFdDF\\E^F|EEh@G?Kf@NnB@xDGp@HXCn@IXI~D@SIF?Xf@jCBxIY~OOjC@vCKzA[_@]Eo@XB\\c@tFc@jEUpAiAtLi@fDWj@m@h@eF?mBb@a@AsB^kHX_D~@aAYe@o@OcALeDIs@Qk@_Au@sCB_Ao@y@cBGqBh@oAbBsAb@m@d@S~AoB~As@fB?z@o@^oAAQu@mCoAyA}A_AsHgByFHyA`@aDrAwANqAE[S_@s@K_BFk@l@mA`ByA`@y@t@m@Rc@|DiDr@IdA\\V\\nCvBn@v@xBbBhCxAz@ZdCNr@Sj@e@ZcAr@qE`@cAf@k@rB_@~BjAtBfB`DhB`AjAdAhBjCbDf@dAd@bBX@dAq@v@D`Bn@dAr@LLx@QtBBdAp@b@j@b@RbBSlCeAN@hF}BjHeEhAIjAu@~AY`BL`H?dBXvFN~BPlFpA|@d@bCtBl@XdAlBPr@Fz@~BbFHf@`@hApAxGJtAFjDMlC}@|Eo@~@_@t@gAnCK~@IfCQh@VlBJ|A@x@MbBAhATpDIbC_@hBw@dBYZk@RoCk@iCuAgBi@oBOcCh@}@v@sAh@}CZgEKq@P_AY{Gs@yAa@c@_@gB[yBaBkBgAaE_FeAgA}DqC}BeCc@{C{@_DF{AEi@o@_COqA[w@WoCu@iC?o@RoBp@_B|@iFlAmE~BqFZQFBAj@FFf@A\\\\NQLPd@FbFoAZQR]dE}A|@Qp@m@dA[PPIEFDBMOII]QL]ADICFYSEQiAl@y@NoBx@kDrBq@Fg@d@eARu@SmAeBF{AJOJBS_EEmDF}DCmHFU?{@JMCSTOc@iDGqD?mBDGGG@OVGSkC?qGGaBJ{@AcBFm@I_MFqGK{CFiDCc@Ua@c@Um@CmIEaCU{DP_BOgDH}EAqDOw@LuGEqCJqWI{AGq@QuBBMK{@NgCGw@Pm@KkCRqAG\\LG@AM_JMmAUEQ{AMiDg@mFkAsAKiGBKIuAeE[mBs@aCDSQIgAaDOq@FG_AuCHXELq@Xq@]BIJP[dA",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.963804092258215,
            -93.29069746658206
        ],
        "end_latlng": [
            44.974267641082406,
            -93.28328149393201
        ],
        "average_speed": 5.835,
        "max_speed": 15.026,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 272.6,
        "elev_low": 252.4,
        "upload_id": 13260562827,
        "upload_id_str": "13260562827",
        "external_id": "stripped_4BAAED2A-35E8-43EB-B6D8-E2BE955C82BD-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 3,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 200.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Short Ride",
        "distance": 11889.5,
        "moving_time": 1768,
        "elapsed_time": 1885,
        "total_elevation_gain": 44.1,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12445833363,
        "start_date": "2024-09-18T21:53:28Z",
        "start_date_local": "2024-09-18T16:53:28Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 7,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12445833363",
            "summary_polyline": "}}nqGnjjxPYoCMt@@d@VA?_@u@mCOeAIQmAuEW]S{@aAmCXSCScAmDi@{AQYSu@{@cA[w@QK]g@uAiCA][?e@m@?OUg@MERUYKg@a@F@GIMBMm@[UCU}@yAwAgBa@y@g@k@u@mAo@e@m@mBE?w@{AQCmCmE{@iAe@e@c@o@a@y@kA}Ae@mAUS}@aBy@gA[Oi@gAk@c@c@oAe@s@E}@_@]Yo@LGVn@BKMc@KFB`@ZFEQz@uA_@L{@WWLW`@y@b@WSQDi@b@gCtDk@f@mBt@WAUHe@f@wBr@s@j@c@|@cA|AIfBQb@aCpAm@fAg@rAQfASf@OlAaAhCGx@DXb@zAR\\L|@DdAUdAUb@g@h@_A^e@?w@[kAb@q@f@q@dAWPIIEc@wJwc@oB{Go@gDGMQTN~@`BxGh@hB|BvKbDxNZ`ApAjG~@]x@kAh@MXYv@E`ATh@Cp@a@Xc@`@gBBmAK}@gAeDGm@f@y@ZgAl@qChA_Dz@y@pAq@f@k@HWDmAL_AFMrB}Bd@]vEsAjBy@rA}A`AoBfAm@fAEXo@JsALk@p@}ANC|AsArEkHNC~@mAXm@XeB~@yCXMHUb@i@h@MTUvAsCfAkAbEmLNYh@e@IGAe@MSG@WnAc@dA}CzJs@j@q@`Ay@pBu@p@o@\\_@n@S`@oAfEYj@qBhBo@r@{GrJMTA\\a@rBc@p@_@XMDi@[eArAa@~@y@dAc@b@u@\\@r@YL_@G{AnA`@tBl@vEXrCNh@FhAV`BLd@Xf@\\zBn@|AAXbAlDh@xCHRt@n@|@|Bp@j@~@dAt@zAp@x@AH@]O[JCEEFDDSh@QBYPJDGs@_CKgAc@w@PwBJU^JVl@nAtBa@YLEvClFXRj@KDW`@c@z@yAZATFjAtAAXJ\\PTDGBPC??GRZNEZoAL}@\\WTHJQAI^[P?RVZLJr@LVTB^hAVBOlAB~@h@J~BbCl@@DJN?\\`@VLFVZJj@zAJr@R?b@MDb@L?rCsB^HFZG`@v@tB^~ANVF\\@f@J@Nh@NRBRVd@l@bCZXCl@d@~@Fh@^rAGNDr@_@AD@KNLHZ[@J@MJ@IOFH",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97391912154853,
            -93.28311553224921
        ],
        "end_latlng": [
            44.973987098783255,
            -93.28289567492902
        ],
        "average_speed": 6.725,
        "max_speed": 16.396,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 261.4,
        "elev_low": 244.8,
        "upload_id": 13269445366,
        "upload_id_str": "13269445366",
        "external_id": "stripped_233A7367-CCB5-4A95-91B0-AB687596C6A8-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 5,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 213.9,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "To Coffee!",
        "distance": 11519.8,
        "moving_time": 1803,
        "elapsed_time": 1938,
        "total_elevation_gain": 34.3,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12479835787,
        "start_date": "2024-09-22T22:07:48Z",
        "start_date_local": "2024-09-22T17:07:48Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 8,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12479835787",
            "summary_polyline": "s_oqGlhjxPDPFHRADUQeAQa@UaABKGIc@cBk@cBUkA]o@@UCOYm@ECCFCs@Y_@CMWQAQUcAw@qB@OVIHIGc@g@eAKSSMM]QUEUkAyAaA_BMs@{@s@_@m@]oAMAAGOUKAMSUEOOs@{AOKC[GUm@iA?GEEBMCMQI{@eAOEWSEG?KEKKOWS_@a@]k@UUSYIa@GK@OEKKHKGBGGCFMe@]y@oAIQ?KS[SIYUqBmDW]ICGSC@Kg@c@e@iAiB{@eAs@iAMIe@aAKIOa@S]Ma@i@}@CIg@q@I_@m@y@GS@GNC@PNZHAWo@GB@FNb@LJ@UOg@m@o@GBY^WLAJiAHKDWT{A|Bk@bA[X}@TQEaAn@K@s@h@}Ab@cAh@c@h@IPIDs@vAIx@Ap@EN_@b@kAt@ITOH{@fAm@rA?RMf@?PGb@[jACTc@hAU~@Ad@Tp@Zj@VdAF|@Ez@W~@o@`Ac@N}@D]IY?e@De@L}@r@a@t@k@f@EJ]Ti@I{@AWJKLo@^qCdAoHtB_AHoGhAsDPiALo@v@i@RIJMb@Ep@Dp@ClAGd@ILJb@@ZERDnCANMFK@IGiBA_@G}@JIIUBWE{ADgAC[Fs@?IGwAEUQm@BICYNaAD}@Ae@H_@E}BFwEAmALsBCqCH{@IkC@yCT{ITcBNwGP_@Dg@CoANsFRkABKEGHUKi@@c@HKHm@DYCq@NKGKFaA@mARW?q@Pa@Ea@Lw@FEDwANgARgEXeDj@_CZQHkEp@kE|@eADa@J_DbBg@PsBrAw@^[VqAh@oAx@{An@cGzC}AnA[f@Ol@KzAAxEAHMP}C@}AJUGo@@_@EOIc@DeBIkAB@BEhA@t@KhA}AdHQh@Gd@_@rAiAdCGJg@^KPGVCb@IReBbDQl@cBbD}@nBOx@Gr@ILODw@B_@b@gAfBi@dBUjBI~@Cl@?xACvA@b@V|@Dd@ErAD|@CRB|CEn@@bCGtCBfCBTAtEEpABj@E~BB`DEhC?j@FT?bAEl@CpC@|DE`CBRAVMh@B|@JhAE|AONEbADtACj@@lC?dAEXDlACT@r@CV@JCbH@r@CzABn@E~@Dt@A`@CNOEMHG?u@`AWNcA?eBDSVEPDhAXzBC`CD`@FHDVF@DOGKAW?NB?X?NGq@N",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97418524697423,
            -93.28278788365424
        ],
        "end_latlng": [
            45.03839255310595,
            -93.32129342481494
        ],
        "average_speed": 6.389,
        "max_speed": 11.216,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 263.5,
        "elev_low": 246,
        "upload_id": 13305818951,
        "upload_id_str": "13305818951",
        "external_id": "stripped_C17EA692-1E72-48F8-BD0C-2343331EACF4-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 4,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 201.9,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Back Home",
        "distance": 11970.6,
        "moving_time": 1694,
        "elapsed_time": 2098,
        "total_elevation_gain": 45.4,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12480231240,
        "start_date": "2024-09-22T23:53:07Z",
        "start_date_local": "2024-09-22T18:53:07Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 11,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12480231240",
            "summary_polyline": "_g{qGxloxPCeABCD[@a@?QCV?mAQ_ALm@Bw@KgBB]JGE[B}AEiA@oEDaBCs@@iB?aFEmDDUAWFuFBUEk@GQSuAAYLkDJeB`@mBXaALGRe@V]x@e@p@QRB@KGa@Dk@Ps@~@}BDSCIFSV[HYV]d@cAT?rAaDNIHQ\\cALWZUd@mATa@b@aBHs@t@qDFSNOZiAHs@FgAGy@@Kf@ATKdBDrAM`AHb@EfABxDQHOHg@?cAD_AAcBLqAh@cAfByAj@o@lM}GbHoDjCmAlEq@~AOlGiAV@tAU`JeAhCKbH}@zBEhCYnA?bE[fAJ~BEjFSx@KfADv@KvGOjCSPBr@Gr@HfEBdBEjFUhEBlAExEHpFGl@FdEIfBB|@GDDfBLDGAIUs@H{EEo@JgACkBN]`@Ef@e@l@Wl@A|AOLB|ASNKjBYvE_@pBu@dB[xFoCh@I|@@LMN?`@u@\\M^a@j@aAd@[z@UHJZPVMAWNKAi@MS@KCMWg@G[Es@@S^w@n@wCR[VaAb@eAd@Un@sBb@u@J_@~@aBlAu@^_@Vg@TqAEy@@WJWjA}Ad@c@h@[|@_@TFRGfAg@LOd@CrAk@XSR[l@qAd@y@XYj@]~A_@d@WLOIuAR_ARg@Vc@rA_Bx@_Bl@o@t@kAdDkDVg@Po@`BkEfAiAJBVM^i@F]\\WRw@r@eAXAbBdBtAdA^j@tAlACJSZO\\Oz@Sf@GBYvA[t@Kj@S^YjAy@~Bc@~AEBMj@?LCBBF?Zo@|B_@d@KVFRMHs@bCUP[`Ac@n@ANJZI@YdAYf@Gb@KLKVGXE@Yt@N^p@~@RTNFPb@XVBPLFXh@f@Tj@t@ZN`@\\\\BXKH@EDXZ`@TJCTRp@]JPAPTd@z@~@b@Xj@p@b@T`@d@FL@N`@L`@XRK`@n@RNHT^f@zBrBf@n@RGN\\LDZh@RLVFFR\\`@F\\H@NVt@Xb@f@pAp@XXXH`@V^b@f@\\d@j@DPGLC\\GHFDMp@BLYXYtAWZGP?XIl@a@xAOXYNy@lAu@x@mA~@Sb@f@nB@d@FBTd@Lz@Zz@Jb@?RNd@NPRv@R`@R~@Xt@Hl@CLHRCPMH?JJBNS@JGMBMUHO?EIBBBRFEG@I\\FgAd@i@HLGAH??IKHNIYJ",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            45.03680929541588,
            -93.30908543430269
        ],
        "end_latlng": [
            44.974026661366224,
            -93.2826064992696
        ],
        "average_speed": 7.066,
        "max_speed": 18.942,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 261.7,
        "elev_low": 243.9,
        "upload_id": 13306243018,
        "upload_id_str": "13306243018",
        "external_id": "stripped_4E4AD8FD-7C20-45CF-B831-EDB9D5071562-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 6,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 180.1,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "PR",
        "distance": 70357.8,
        "moving_time": 10176,
        "elapsed_time": 11010,
        "total_elevation_gain": 273.8,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12486708135,
        "start_date": "2024-09-23T17:27:21Z",
        "start_date_local": "2024-09-23T12:27:21Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 25,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12486708135",
            "summary_polyline": "w_oqGxijxPhAf@\\YmNsc@}GqKFq@i@HsMgSQoBqR_X{E_J^HBI{@yATeBrHmMrHsLfGeItFmP`B}@EqObC_I\\gF?yMy@aG~@sSj@kBvByBbId@tEoBxK]~I{GfGePrCqWjDsTrB}GbFeHlOqMlTkWrKiOlLwWbCsB}AzCtFxPjC~WsAzuAtAdEdCpBwB~EnFdRHbVrEjMvAdM[frALbpAn@`Gc@tBEr\\T~xB{CbgAE~TiG`@{CkBi@uCoDwEQuLgQvAcBcBSyHqEk@aByAe@}Cp@aC~GeGpFmAB}CaBoCeMkDkEF{GzBoEgAHqDlM}L`PzK~Cr@rCaAnCkJhDe@lKbHbHxJj@dCvC}@tDrBfDEtB|BnK}C~PiJr^rAnLjGlF|M`BpIzArBxCI|FwCdAsCxPkFUmSv@_KxC}OdF_LrD_CfOJz_@dQdC`CdEbMnBfLi@pV}BjPgGlLkFtBiPyGuJyIaHsAwHqE_MaCmAeGqEzAsB[wAl@kAnEeE`DgGXs@~@g@dLeE|J[`Fx@`QyAjIaBp@}MoDmHzCaHLiMiAqIcDsQgPeB_CgBcHU}E_DiO|B{M`G{PL}\\b@mCq@kYRqa@jAmAi@[dHU\\oNzTVb@iOtt@Ld@aGnTLd@kx@`UTFpUvAx@dPD~bAp@hAvCy@jNA`Fx@~FDzHlGf@hGgEB_MkAm@iEC_A~@x@dKyAyPLgJeDoCeBkG@eCpA_CKsd@l@kGe@cO~A}EbC_Cd@eEiAwEm@}JuDiGwCcMGsNcAmHwIwLgBmOh@cNKqPQ_JeAiHImZkBmAwBf@iCoEcCk@@aDfC}O]{Dqt@WBgb@kl@r]LsBFkBi@}LYajCyGp@kHpJcC`A{@g@eBwFkBwAgNZgBcBgFkAuLlA{FbByPtI{BdCoLrYiF~IsEpEqAdCpDbMsDkL`B}BmD|AoJ|UyKzOcRhUaQrOeGxHsCfJsI~n@gDbJkDxDgJhEgHC{DjBaJMwC`E[~Jj@F\\wBxC{@`@gDkB_FwLuKsA_GwCyu@`AmPxFKb@mClHvEtBkDnEFbAwC~HDYrAZwB{@dASrGBhd@UbBs@CHvQlAdA?bEdEp[lEe@`Cb@lAjBtBAM`LY`AsNr@wO]qKeH{PqEaGaFvAmDpCvDia@vsAtJpIjJf^~KdKoA|BcIbWeI_MkCiFl@^w@gBgDdBwCpEaIfC{C~D_@xC_DdC}AhDgB`IlA~Gk@dCiAx@iDg@vCl@`CuBNuCeAaGfC_JvEmETkDdC_D|KqFj@ZrBsAhCtDpBj@nGrJ|AaBvBiGn@GtAaFhAB",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.974207961931825,
            -93.28300539404154
        ],
        "end_latlng": [
            44.98025642707944,
            -93.26597588136792
        ],
        "average_speed": 6.914,
        "max_speed": 15.491,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 287.1,
        "elev_low": 225,
        "upload_id": 13313184064,
        "upload_id_str": "13313184064",
        "external_id": "stripped_1E135ABF-9A82-4C87-9424-5A45327D393E-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 15,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 192.9,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Flat Tire...",
        "distance": 23930.6,
        "moving_time": 3177,
        "elapsed_time": 3263,
        "total_elevation_gain": 86,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12504630682,
        "start_date": "2024-09-25T22:24:08Z",
        "start_date_local": "2024-09-25T17:24:08Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 16,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12504630682",
            "summary_polyline": "o}nqGvijxPGF\\LvE|OPfAlA|CPtAWn@TtBHdEOnLFPl@HLd@UnAMtFF|@f@bAhAb@dH?LcADaSNQl@L|@OfBo@JTDOl@d@f@B|CmDj@gDNMbCh@c@dCRjFIbBB`@PXtCTKWJ?jDn@rKT@tCI~@FPQ~ALt@?dDEzBQTFn@G`BNj@NbGOhFO\\PPB~BAb@SXFb@Wf@`@X?hA[tFcA|DK|AFh@XJVf@^cAzEyFxE{Dr@IbAZvEbEnFzDbDp@nAKt@c@b@iAlAuF~@_A|@[nCh@`IhFbCvDzClDv@fDZ?lA}@z@@nDzBrCOlAf@j@p@~@P|B_AnIqCxGsDnCcAfBc@bJAjQdApDdAzAx@pD|CpFhLdApJp@hAx@j@pBHzBi@zAoB~AQ`@_AXcCv@{@vAG`@l@NY`EiBtBNt@m@@gAa@mG?uHViEvB{OdCeHpAyB|@yBfAgBjA{@hB[vGKtE`@rCx@lV`LlBnA|CvCdBxEvApFr@lFJV^FPGOc@AkAi@oCeAeDwA_EyA}C?a@ZXdBKr@_Bh@sB`AkAfAUbALrI_@fAu@tDFdA_@zA@~Bu@bE}E^q@fDeBHeBm@cGNi@BwBt@yCByCa@yB`@qD_@wCo@}GLiEb@cBp@sAxAyGT[jA_GlAsBpBAj@OT[XwCQiD^oDIiAc@kASwAu@aAy@UoBXy@[c@mAVaASqAcAcD_@c@w@uBi@a@u@eBqCgDEw@k@mB}@}GI}D]uAk@e@}@W_CE{CcCJ_A]sIEsCJgA`A_Dz@k@bBqB`@qB}@uK[uAk@yDeAkA_BoCi@qCi@wAgA_Gc@}H\\yDo@gFaAkCo@cAs@i@]sAyA{@oAgB?sAk@{C?eAWaCi@_BCcFZeATqD@}EQqE?{AVcCc@wAM{Da@eACcCSeAFcAOwAAsGWoDX}Dy@kAEi@a@c@x@z@rAPjAkAPaBm@sBGcAc@iBH{MCeOK{QLuRIgZc@eEEgHk@{JJ_AkAsBMs@cAs@k@cASmAHcDOqAs@qC{@w@w@wA_@}BDy@QsB{EsPq@_Aq@WeD^iDK{CjA}AjBS@sBi@mCeCoEsBqA]eBoAcBq@cDg@kJbA}E?oHQkPhBwCdAg@b@oEnGuBjBcAMo@a@a@gA[mBe@eA{B}AqGf@cDGg@IoBgBaFw@qDH}FrA}@B_EvA{B`B",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97384812682867,
            -93.28299407847226
        ],
        "end_latlng": [
            44.947468768805265,
            -93.20440317504108
        ],
        "average_speed": 7.532,
        "max_speed": 14.3,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 277.8,
        "elev_low": 242.9,
        "upload_id": 13332232406,
        "upload_id_str": "13332232406",
        "external_id": "stripped_29713A79-7FBC-4E9B-936B-3AA0AF6DA9A2-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 5,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 198.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "17+ Average!",
        "distance": 30726.2,
        "moving_time": 3914,
        "elapsed_time": 4031,
        "total_elevation_gain": 146.8,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12511606923,
        "start_date": "2024-09-26T20:25:09Z",
        "start_date_local": "2024-09-26T15:25:09Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 48,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12511606923",
            "summary_polyline": "k_oqGzhjxPGO`@v@^ITN`AnCzBvIvCjHJtACWMREp@Xd@j@ThGFn@PzJ@lEn@\\nAbBLVTHlOJh@xDPxCQtJFHPBrIOj`@BxTOx@kAnAQnADr@n@l@b@oAdD}DfDiDbBgAp@E~@VdGjFjEzCxAh@|ADdAQt@cAdAgFh@yAv@i@pAQrBn@xGbEh@f@vBdDbD|DdApDxAkAv@?tDrBnDKdB`Bz@RxEoAzJaFxDeBpEsAxI@zQfAtE~ApErDbApBTpAhCbGhB~InAhBv@Gr@RxCm@Te@dAeA~A]R[b@{Cd@q@zAQn@h@T]pD}AfCFn@s@WcIEaITqEjA_Jv@yD|BaHlDiHp@}@hAo@|B]bGAtDX|Bj@nX~LlDnCnAf@f@_@nAQnBgFf@k@r@UtLIb@YTi@xEUv@rAZP|VAjBOLiHAuVCmLQYwCMNwDCiGSSkBAdCKBcC~@cFVsD\\aBLmEPsAt@iAxBaAx@qBJuAQkC^gFAmAq@mCuAiCs@KuAXq@SyBiIoBkFaCuCgA?DmAo@eBk@sC]sC_@iG_@oBw@w@oFoAcBuA?_C]{JDuA~@_DfCaCn@kANq@IwCmBqOiDwFkC{Ka@_Ae@{FLiH_@wDu@uBaAqA?ON?o@k@Y}@uBiBm@cASgCa@iB?cAUcCk@yBCiD\\sBRmDEaIUiC`@_Ei@aBE{D_@{@E}BW}AFw@ImABkGUkEFgFOw@N}B|@eE?_FM[PiAG_BA}tA_@iFG{Hi@mIFqACUoAqB_BuAg@iAQ}ADwBKeBm@iBmA_Bm@wA]kCJuAI_A{EeQq@y@s@WwC^kDKoCfAwBxBcAR{@W[cAq@_A{A{@eCqAiCw@qBkAwDoAuCBwIfA}@?}@]yHC_LdAsFdAoBrA{BnDwCbDyAZeAw@iAaEkA_B_@Qs@SoFj@gDCaAYu@aAy@[_Do@yBI_LbB{Bn@aA^wJnGuDt@}@l@gBnCgElL}BzFsJbPkHnGmExKyEvJuCnDaFzHeGhGwGjJgErEuMfLoFbHyAtD{@rE}CbSeCxU_CpH{BrEwEpE_CjAyEx@iEAeFnBwCs@sA@cBd@uAjA_AlCGbEWjAL~CQ\\YjEBrAl@fDOtGP`EMbEQhAkAjCg@nBgAxPSl@o@lAkEbNeBlBaAhCs@Ru@r@gCdH{C|C_GhI}@xBg@~BwCtAsA|BQFFOgAvAgIbDwA`By@`BOjBgBnAoBzCaCpJGd@Fb@v@rBJv@?~A[fAu@bAw@TgCQSe@ZE",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97414912097156,
            -93.28285183757544
        ],
        "end_latlng": [
            44.99139220453799,
            -93.27421822585166
        ],
        "average_speed": 7.85,
        "max_speed": 13.63,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 277.7,
        "elev_low": 225,
        "upload_id": 13339675893,
        "upload_id_str": "13339675893",
        "external_id": "stripped_0FAE6169-57D0-4571-91A8-9B3E4412CD1F-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 27,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 215.0,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "To Parents' House",
        "distance": 42721.4,
        "moving_time": 6247,
        "elapsed_time": 6468,
        "total_elevation_gain": 199.5,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12536628233,
        "start_date": "2024-09-29T22:10:55Z",
        "start_date_local": "2024-09-29T17:10:55Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 13,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12536628233",
            "summary_polyline": "{_oqGlijxP\\HLSa@aCk@{@j@y@eB_GgEnCyFhBsKDKeAe@_BgEoFwB}EyDtEoDoFsAgD_CtBcCcEm@Y_FwJ{@o@oDaGr@oBhFoHtH}MwBqFrB{Da@cAuDiCg@CoAbBa@y@hAuBrCyAtAyEjLcO`CcGdC}BhAoChAgArGgRn@yNt@uDbBqFJoRs@eGl@_GOaC`@aBAgDbA}CdDmBjGh@zEiBpFAlDy@vB_AtEcEfCgF|BqH~CmY~CuRpBuG`H}IpPeOhJgM~EyEtKmO|KiWtFsExCaE~FkK`JcUrCgD|Cs@bMuHpP_D~Ff@pFnCxK[bBlAbBjFrAp@`CsAzE_HrA_ApD_ArOuAdLVzN}@~NdGtCnBz@dBn@P~@KbCwBfDqAfI@pAxAxEtPBzC`@zBzC`G`@zI~C`EIjBb@|A^tHJvHi@bDLpcCn@fLPzLRpg@l@vD`ApCzFhHpAtCj@pEGbHn@~GlC|L`DbG|AtHMIXN`@rJ}AnC}@^eBbGf@fQhBlApG~AhAvMfAjFt@|AhBtA]KtDrHfAfEh@zEjAXpBa@v@^n@fAv@rE[vDLhCS`DiAp@iBB{AfCgCpLaC|HKtGt@dDTlDYdEX`CGpB}@xI\\rIyDfCkApAyB`DuCv@wZXgB~A{AbEcBfBpD|KtBzKZlCDdIe@jJsA`LeCjIsD~FgFpCuDyBwFkAcHwEcCaDiBgAoGeA}IeFsKuBw@yFoACmEvBi@k@sAPy@dAs@`DaBXwB~B}D\\aBx@CrDq@xEyDdKWpEh@xDQlERjFo@~Ew@~AiB`@mMeD{AJyDxBqBVgPq@iHmBkDoBmJsJmHyG}AuG?_DoDeQ~BmMtBsGzBqEgEQeA{@cD{@yAtA_Df^iA|Ep@nAJpC[~UaA\\yCwABzDuA~CKzEz@bG@jCgAtP}@pDuBxCyA`FeCtBuDY_BoAeAIsFTcD~@aBM{AeB{@gFm@kAq@c@uEG_FyCyEMuDzAMt@r@rB{@{BiPoNsBaAyBCwBd@kGpD{GdB{@lBeBxIgAlBqB`BaC\\}N}BsAjBeAKiEtC_AhBiAv@cHfAkLFiEqAyBoDu@c@{G^uBw@k@}Aw@c@qAKaFlBsC]oAqE]gIcD{E_@yAPiCeA{AaACqBnAiHwBkBBeBd@cCpBiIpBqEdBgHyGcEiRgF{EyDyAkI~G}DkCoEiAwC|@}Bo@aBl@iAg@}@nAiAjFmAbAsBV}J}@qC}@mBRoDtBiHLyk@VUsAYOsjAp@e@bAQ|HmE@}CiCO|ANv@PE",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97422128915787,
            -93.28294169157743
        ],
        "end_latlng": [
            45.03831728361547,
            -93.3213937561959
        ],
        "average_speed": 6.839,
        "max_speed": 15.54,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 290,
        "elev_low": 225,
        "upload_id": 13366394071,
        "upload_id_str": "13366394071",
        "external_id": "stripped_32809688-288D-4E4D-B415-B735CF2130F8-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 166.6,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "And Back..",
        "distance": 11072,
        "moving_time": 1612,
        "elapsed_time": 1725,
        "total_elevation_gain": 32.9,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12536790695,
        "start_date": "2024-09-30T00:20:47Z",
        "start_date_local": "2024-09-29T19:20:47Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 5,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12536790695",
            "summary_polyline": "aq{qG~yqxPD@?E@@A@CUI]?cAAeAI{@GoA@kAD_@FAZDJ?JIJ?JDL?x@AZERSb@e@TITMFM@UCy@BcOAiCDiEBeLA_AEy@D{@BaCAk@BeHAi@DoI@qRBkEBk@Cq@B_AC_BBeAAg@BWCiC?yDDuCNkDFi@XmA^gAd@aAJKXUh@WLC\\?JEFOD_Bb@uAv@iBFIDOf@{@`BiD~@{BPi@JOf@e@l@qAf@iAlAmFBWNi@Jm@HOHg@Li@BS?c@A_ADENCXSHAhC@`@AnADl@AZCZ@|DMXmADcA@sCFo@DYb@y@JOhAaA^Ut@m@z@c@t@k@lAk@\\SFId@M`@QlBgA~JgFn@a@|@Yd@Gx@Ev@OlFy@dB[n@IxAWtFm@v@MN?`BQjAC|@Wb@A^GxAKt@OlAEv@GzCMPKPFvEQL?ZHhAAvFWd@@jAKzESl@?XG`@@tBKJ@t@ArCOlAAhABrBGx@BrB?l@Cj@GhA?x@?NB^?JFp@GL@hACPBLCn@@j@E\\BdCCrB@|BArA@x@AtB@r@EzA@LCLGHKHQ@UBk@A}EAo@BQAkABg@XWXQp@i@ZMx@AZElBKf@G`Fw@hAMh@MnDgAdDmAJ@ZQzBw@ZEr@DDBTCPIFUFi@ZOFGA?DEFWn@k@VQn@UXACABAGAd@Al@NVCb@Kl@a@V_@JUDULW?BBBA?CCHIBIBYA]G]Ce@EQUw@S_@Oc@CSCi@LSNe@l@sCNe@h@{Bv@_Bf@o@RO^Qf@c@RIPq@FgAFa@Xa@l@eAh@q@d@Yz@a@|Ao@~@YjBw@VSd@o@FCH@DFBLDDJBNA@SFKd@i@HCLSJC`@NVBDHTNBHLJ^j@BHVZFD^C^h@n@d@^t@\\`@NXTVVh@\\^Zf@FBFLRR^v@Xd@L^d@b@f@v@JJj@`ALF`@t@`@n@Z\\Zv@JDPVl@lAv@bAVRVf@X\\BJDBJTBJFBjArBRRFJDLXZHRBBFXTNj@~@JGNVXz@LHLVDNR\\VTLZZ`@DRNDTPDN`@f@HRr@fATXHFFNn@x@FLFDTp@h@j@h@`ArAhEXp@n@bCrAfEb@zAVnAJTBRHRJP?JHFJVRp@Jf@?f@CFODCF?JF?DC?GH?C??B@BB?EA",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            45.038416273891926,
            -93.3214315585792
        ],
        "end_latlng": [
            44.97399179264903,
            -93.2829402666539
        ],
        "average_speed": 6.868,
        "max_speed": 11.922,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 263.4,
        "elev_low": 246,
        "upload_id": 13366568903,
        "upload_id_str": "13366568903",
        "external_id": "stripped_5329B76B-35D7-4B39-AFED-C59035433BD5-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 1,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 172.9,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Pre-Gym",
        "distance": 37788.3,
        "moving_time": 5074,
        "elapsed_time": 8318,
        "total_elevation_gain": 148.4,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12552723555,
        "start_date": "2024-10-01T22:07:00Z",
        "start_date_local": "2024-10-01T17:07:00Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 25,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12552723555",
            "summary_polyline": "m_oqG~kjxPJmAfAp@X}@hDcB`@nCfBLn@Ub@qAhABrEaDrNJg@zAaAfQ{@zC}@x@c@xADvFxEf@bDr@dAjHZPk@dBN\\bEb@rB~AxAe@jC~A`Gn@Fxf@i@rKlAlDyAnDk@rD@pB`@fArCwEhFeFhB{@jAJvMrK~Ep@`BwAnBqIxC{@hLdIvFhHxArEpCm@zDvAxDBfB|AdATtGkCn@aAhCk@pEgDtEuA|B]jZ|@tGrCpDdDlAtBPdB~DlJn@dFnAfBxBFrCq@dAgB~@JbAwBbCO@cArGgDdCDj@q@WcTp@wJpAsH~AqGbAwBtDuGlBsApK]zF|@tPpIrFdBbGbFpCu@vAqEfAmAfNa@`AaA~CUn@Fl@~A`@LvJSvB}GdCeCz@{BHcCa@cHl@eICsDf@eKWy@HsDpBgL`DuA~@eDVsDW_DdAsOqBoImAaAsAf@u@Qy@uAk@kEiBkF{DwFk@S}AsHi@kJg@yBgH{B_BmAD{EOkK~@mD~BgB`@}@XwAKyBmB}OiDqEeD}O[wHTqDs@mFwD_HwCyCwAsMi@gBEsDv@cHY}M^sDg@kBCeDc@qBc@mK`@u@Tz@OpDfBrAIvCZlEt@x@vFnC`D?hAw@n@JXnArFzCtBtHtBfDjDrB|@rAtClFg@d@r@|AtAdAhK|CrAvApBXlBlCdBB`AaAfB]fAuBpAqHD_DbAkBj@gD?oGeCqKgCmF_EyEqGoBcCgBeAwBgCcCYcDy@cB_Cw@}FuDaEWqFoByDcEaBLsBaAwB|@oCxFaCbHiAbO_C]QkWd@iCq@FjAsHCy`AIq`@a@yMm@kKNcA{@gA]{AkBiB[_BFmCYqCe@yAsBqCYcASoFsDiNyAqCsLL}D|Cs@H{GkEwFmBgHaDmMfA{MY_M`AeGxA}GfJcCbAcBaAu@}DaBkBuJb@_C[_CeBkDeAkFPyNbDyKfH}Ch@}@t@}C~Hk@j@m@tCcJbRoEfGkDtB{BdCuE`MaElIuCbDcEbHqFhFmKtNwPlOoDzDwBpDuC~Ld@X@m@[Io@rDeDpU}@tKuC~JeHnIkCfA}@?pCmCqDbA{DNuJzEmEs@wEfAs@dD@~CUXWfGm@|DAhB`AzHBwE@j@YrKN|FHmBCdAG_AmClLkAhSsGhRaAl@qArCmBzAwCfIoDjD{FpIeB~F{AAeClDV?X`@|AqAp@@x@p@v@~Bf@Sx@`@lH|L|CfDnDxGvCdDGn@lDlDtAtBdB|CJ|AvIzK`AbB|F`QjCnJOlCNrB",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97415591031313,
            -93.28335533849895
        ],
        "end_latlng": [
            44.97406748123467,
            -93.28379161655903
        ],
        "average_speed": 7.447,
        "max_speed": 21.134,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 277.8,
        "elev_low": 225,
        "upload_id": 13383603384,
        "upload_id_str": "13383603384",
        "external_id": "stripped_7D9D699A-E369-44AF-A2EA-DA30AA568A12-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 4,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 179.3,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "First 50",
        "distance": 80743,
        "moving_time": 11475,
        "elapsed_time": 12185,
        "total_elevation_gain": 260.7,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12560894679,
        "start_date": "2024-10-02T21:08:20Z",
        "start_date_local": "2024-10-02T16:08:20Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 56,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12560894679",
            "summary_polyline": "w~nqG|ijxPoBeL_DmEAuCkEmKd@a@ik@a|@uDuIED{@kBfA}DxKiNlCaHvGuIpG{Q~@yOzCcLDkRu@wEv@_GLgMjDyEtHXjFqB|GKnFkBpEeErGcPfC{V|DaVlB}FrZe[r\\cc@jL}WpHoGzFeJrMg[xB_CfQuI|QmDlMtDrK_@zAp@vBdG`Bx@pLuLbSqC~]k@pPdHzEpEhIwE~JLdG|Rf@xGfDrGb@bJtCbD\\rEh@vQk@tDj@zkClC]d@pIhCfDrCpA`Gg@vGvErEfMrExCzHtNlQhHxBjCpFoApA{BnAgLjB{Fk@wMiAeGyCcGkDyDqKcFoEwFsAoGcHcEyNoD_F{D}Dq@iCbA_GxNuArOwBZWeCrB|SE~R[nEo@d@d@pO|B|HzBrDfBb@dBpDdAxV|CxMjDjGnBzPO~CgDtDkApE^tQzJbEtAvPrJnQjB`K~F|@hBhGc@nNgDh@qAnB{GrVI~HhAtHKlNaArHh@rIkDtBmFxGoO~BwMPkD|GgCjAtEpNzAjJJfJ_CrXsCpJkCzDsFvCaL}DkOwLyGoA{IaF}KuBk@mFwAYwEfCeC_@kBnFuErCwGpAgA~LgDzH_@tFj@bFA~LuBzGmO{CqJvCiRw@iKeDsUgU{AyGmD{UvDmQlDkIfEbAz]iNpVv@pIbBrFzDjGfPpAfHF~IeAnG_DdH]pEl@nSyA~GcBl@iNkDgJ|CoPo@{MsEmToTgGk^bCkMfFoN}DAiEsBaCfAaCxZmBbJa^lDmBoB[}HmGqA_AuEpIqJhF{@\\mBy@uCqBmB}KeCmR`Cy@}@MaCfMoN`BDpMbKnEv@tBqAhBwH`D_AvKbGfHnJfAtDlBn@oBb~@lC~ZvK`QpD\\h@~G`GzN|A|JN~RbGpc@JdGnb@jfBz|@~uDu`Bc_HEgF{Fgc@W{S{BwMyEeKc@iGgFmAeHaM}B{IwAqWbD{uAI{_Be@d^wGW?sKe@aBuyAOcXgEiIFcReo@hAOeAm@{AuFue@it@}NeYeDdBgDnEeKvEuBhGiEpEsCxKlAbFU|CwAtAoDDuCtCqP_t@|LqIbF{NzVqNpGlH`HpSdD|E_Lo\\}Hu\\dFeH|M`KzBtEdFdU~B|DuK_a@{OiNjF}MPoClVwx@jJvFpNdDdJhGfGRGoAoFR?gIoCBiAyH{LgLwBmFxBpF|I}ItE{ARmEzEi@fE\\`Fpc@rEo@rCf@dDlBEfMdAvA}BxFkPb@gM~`@{@NX|@_[`aArDjEeBpGeBbHvMrM~D~AbGxF{AnDHjBrPfNqExNkEpEjGbWi@`FqDIWkIxCsBzAvEWfF",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97404518537223,
            -93.2830301206559
        ],
        "end_latlng": [
            44.97396153397858,
            -93.28407425433397
        ],
        "average_speed": 7.036,
        "max_speed": 14.314,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 280.5,
        "elev_low": 225,
        "upload_id": 13392327628,
        "upload_id_str": "13392327628",
        "external_id": "stripped_EBE83A7C-B530-4528-B604-A8AF66EC40BB-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 14,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 243.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Late Quick Ride",
        "distance": 12223.3,
        "moving_time": 1676,
        "elapsed_time": 1733,
        "total_elevation_gain": 46.7,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12568949029,
        "start_date": "2024-10-04T00:06:06Z",
        "start_date_local": "2024-10-03T19:06:06Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 7,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12568949029",
            "summary_polyline": "s}nqGrljxPk@oBHm@Ge@i@uBAk@KIq@gCg@qADDYw@My@kCcHuAyEg@w@e@UiB}DSMCSMASc@c@CWe@K_@iAsAAcAWw@?]a@QcAqBYQ{@wAI_@s@s@NEMUc@MiB{BQcAa@U^AJc@m@qAo@]_AQSQI][QIc@@FW]GYE@bAcAh@WEc@QZCMU@Ce@Ka@BHFUMBGQaN}McAkAASqAuACMtHtLk@aAeAeAw@wBf@TsBaDWS@ZJ@B{@_@MWc@]T_@j@qBViAvBYdAQ?u@|@oHrBgAr@cBxCE|AYbA_Av@cA`@g@z@eAlCi@rCeAhC?RjAnDRvAIhASt@cAhA_ANWPY?Wi@y@NuAx@c@v@?Ta@R]f@q@]w@A}A|@}ExAgD|AeBf@m@?kHnAi@MqCJYR_@p@a@N{@Qw@qAm@[}AD_ACeAe@}G}@qA}@u@PgCrBM@M]I@Qz@Jp@t@nATHG[]]NUh@]b@C~@w@lAI\\i@JA|@b@~@GrKbBj@TGNHTj@^DPP@hBe@l@i@~@?fHcA`ACxDk@d@MZ]|DoAnDyAbAUhBGPs@vAcAr@iAp@OfABl@[HULATa@Eu@KWd@WXs@f@q@v@{DDiAh@iCXy@ZB`@}ATi@PoAz@iBNaDjAwB\\c@t@c@rDaBbCw@dDwE~C_APs@As@Ju@Pk@PM`@}@l@_@ZAxA}A`@kAhBqCf@Q`@FR]vAqG^cAr@}@lAk@H_@\\Y`A}BXW`@@lA|@@`@\\b@GZQZk@fCm@hBmArBs@rBEj@Yr@?RgA|AN?FHEl@Nn@zCvBHZSp@e@r@aAlDw@bBYF@^a@nBDFS\\GQGb@e@jAECK|@Sf@L^x@\\JTfB~AJVx@f@fBfBVLVMELKG\\R|@lANAPVd@?xArA^d@RI|@r@^AVPPb@t@JV^h@T@X^\\@ZjAvAjAl@LQLDGJPQGZFEYRRRV??Jt@d@h@pAlAh@d@f@VJdA|ABGHHFZHYb@Fh@n@Vv@z@r@Pf@EHDLEAU|AeAhBEn@OTPUITBA@d@}@d@mB~CiAn@SRG^FlBLz@EdBPZTF\\`@V`Bb@|@Z|AZr@^tA@jA^\\Yd@ClC",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.973860112950206,
            -93.28345332294703
        ],
        "end_latlng": [
            44.974026661366224,
            -93.28399353660643
        ],
        "average_speed": 7.293,
        "max_speed": 20.259,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 261.5,
        "elev_low": 243.5,
        "upload_id": 13400943711,
        "upload_id_str": "13400943711",
        "external_id": "stripped_52FCE672-B770-4780-8600-871B4C3C04D2-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 4,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 239.0,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Nice",
        "distance": 64608.3,
        "moving_time": 8820,
        "elapsed_time": 9582,
        "total_elevation_gain": 194.6,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12584517794,
        "start_date": "2024-10-05T18:53:38Z",
        "start_date_local": "2024-10-05T13:53:38Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 65,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12584517794",
            "summary_polyline": "{~nqGdijxPdAe@_Ls^}m@}_A_EeJ}@aBhAeE`LoNtBmGzCmCpC}EdGiPjAcRpCeJHqRw@mFx@kGYaDj@kHvAmCvBcA~Gf@bEgBrLy@tIgH|FmObFua@zBkMrAmDnGgInQmPd]qc@pLiXfHcGxGuK~Ns\\fR{JxQuDrGr@lD|BlL]dBv@rBzFzAbArB{@~HuJrT{C~LXvNcAzPrHfEfElIsEpKT|FrRR~ExDpIP|HlDlEz@F\\jBdBsAsClCp@`TeAvAb@plCtCMpAiObG{NhB}@~Ep@~DlDxO~DpGxDhAjCZtClErFdJ`E`FzEjCdG~@vEl@~NiBnGBtBoArGsA`CoFjAaCsCoEwBsJgDuGiMaFgDsBiDmBoHaHeF{Fd@aDuA}BuCi@yI_Ch@|ArNYdEY`UFpFnBxOlD~DfDtGp@nFMxFj@hH~CnM~CfFnBlPI|DkDvDcAvDVpRpCpBnFpA^jEGt@r@zGrAtDzFpIzC|MzFbAfBlHe@|LmDz@cBtCeGxVCfGbAhHGvN_AtHZdJoDlBaFpGyLx@sAfAeNXwCvGiCfA`DzIfCtMDnQ_BjQkCfJsCfFyExCiBIuNaGgKgJmHuA{KyFwHiAu@wFiAUaFfCc@o@yAJgBlF}AXwBzBaHjAaAbMoDdIc@dFr@dSs@`Fy@xAyCFcK{CmKzCqSkAaKkE{ScTqAaGoDmVbCoMvE_M~@?bAtAbAUxUkKjGuAvWz@|GzA~F~DnGbPjA~GHzIeAnGeDnH[bFf@vDHnMwAtGcBt@uNmDgJvC{Pm@iMsEkRgQgAuBuAaGiDqUrC}NdFqMiEHgEuBuAl@Lz@y@]}Cn^{AlFqX|AiDfAoB{BWgHmFcAgBwDj@iC~GuGtFoAZoB}@kC}BoB{HkByGDeHxBuBIeAkADeDdMeMjBZnMzJ~Dv@|Am@tBqIvB{ApMrGrHdKv@xCfBd@J{@j@am@S_aCb@_Ce@aAAuDFicD{AeNuEgMQqVw@}@mDwO|BqEsB{AiB_FpAqtAWoIqByOoFwOhBeCSY}C~BaKbVgK|NuT`XmQ`PoErGcAtCoD`TmD|ZgGxOsIzGkLr@gFlBiFm@mDtB}@dCMbLi@bEDy@X|GV@BlT_DtJsAvQcG`QgDjFeBhAuC~HoLdOuAjF}Bn@}ClEcKhEiB~COvBeEbE}CjLnAvF_@xCqAdAyDJuDxD}ASsOlFuPbB_BnAYc@j@nAlAmAbRyBjNyEdBN|@fJBzVbAr@lHsDhc@sp@~HvKg@FbFxF~CgEvCvDhBuDn@QfGbLhEjDtGjRrEyA~D~Ne@d@WtDcDYUgI~CwBz@`DWrBNlMsCFi@kBUyNrA}AaBwFyArAjAnE",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.974063793197274,
            -93.28290338627994
        ],
        "end_latlng": [
            44.975192081183195,
            -93.2822494301945
        ],
        "average_speed": 7.325,
        "max_speed": 13.604,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 267.4,
        "elev_low": 225,
        "upload_id": 13417005508,
        "upload_id_str": "13417005508",
        "external_id": "stripped_9941ED2C-6EBA-48E2-A274-D9ED4182941D-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 25,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 263.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Recovery Stroll",
        "distance": 20779,
        "moving_time": 4900,
        "elapsed_time": 5739,
        "total_elevation_gain": 117.6,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12594114618,
        "start_date": "2024-10-06T22:17:40Z",
        "start_date_local": "2024-10-06T17:17:40Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12594114618",
            "summary_polyline": "wunqGdsjxPiAxANr@p@dB\\xANRr@hBZrAZjB[EGJHlANC|NFdAGb@FXGxBJbAVHPfBDLj@tBb@JLArAGh@DHC\\LvEGzKBh@HJJA@GMYKXJj@G^CpEHzDBJFA@V\\HTIzDGfBN`IGf@@PLGxEBbIE|HBtDJNKfA?tEEj@eA`AYt@MhAN|@h@JH_@Vk@zEwFdEqDl@Ob@Bf@RpExDvBbB|CnBzBd@~ACRI`@e@\\o@z@iEb@qAh@m@pA_@r@BtAj@vDtCnAf@z@l@zBnDnApAdAtAfApD`@GTc@PK`AQtBbAlAx@pCMd@Jh@\\h@x@v@RrAWnEyAv@a@N@~C}AfGeDf@ItCaAdEOvB@pSjAxCz@bAf@dBrAZ`@z@f@p@|@@IMG@KE?@HEOIJr@rAVxAvAtC`AbCd@lBr@pEh@bAd@XJT~@?b@JjAKpAa@VYJ?Pa@j@g@vAe@PWJc@LmALe@l@}@n@Mp@@^h@V_@nD{AlAEp@Pt@o@FeAWwF@iAI_BH@E]DIG{AJ}Cb@qDFq@ECLe@b@oD`@{Bj@{B`BaFnAwBzAeDt@aAp@c@tBe@vFKhBBfCb@xE`B~DpBzMtF`C|AfAdAVL^h@t@dBZ\\?IIAUy@AQ[e@BMbAg@r@?f@o@nAaE`A}@nFKdAKp@F~@?x@If@c@BUpAICgBDw@CIHuFJ_@@e@?_LFUGo@@oDFi@G_@AgE@oLJuBE[E}LDaBGeGWwAWc@Oc@GkCD{Dr@oCN}ACuEHQL@QOHJr@Nd@XLL^z@J|@CpBYfD@v@JFDOYWI\\ZFPf@HpCb@xAP|BXCRRJ\\JHNCPZ?PGNSDOIESH]EUKGi@gAEw@k@_CM}BYwABeBT}CEmBo@kAkBq@?aAO{@cA_CaCLsf@Woa@A_FFmBIi]FkAKyBHyEAk@ASMm@N}IBaGAcAS]JsENaAGwGCs@FiAIiHDmAG{FFgF?oEY[LuHBGIQFAJ@rHEfAaTSUHu@I{QCcAHkHIm@BAZDGGsAFmBCeDEEk@[gCEUQoC@sAPgBO_D@OSB}CIg@[MgAB_AKk@J{AEaAPuQ?kH_@{N@MJGt@@hBQrBBtCHREnBHl@ExABhHIv@_BZsCtBYJMSgAmDSWKAwBbBALWCWLe@v@P?V[BWOCa@nAg@AoAjAMBGYDO]f@[Ni@?MUPXC?ATCC@\\",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.972605761140585,
            -93.28450818546116
        ],
        "end_latlng": [
            44.97415683232248,
            -93.28322248533368
        ],
        "average_speed": 4.241,
        "max_speed": 10.988,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 294.7,
        "elev_low": 250.5,
        "upload_id": 13427114883,
        "upload_id_str": "13427114883",
        "external_id": "stripped_BAD9EAE0-5AB0-4FF6-9BB2-F01D7E3BC83D-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 201.1,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Quick",
        "distance": 33793.9,
        "moving_time": 4336,
        "elapsed_time": 4468,
        "total_elevation_gain": 140.5,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12601407102,
        "start_date": "2024-10-07T21:59:42Z",
        "start_date_local": "2024-10-07T16:59:42Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 55,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12601407102",
            "summary_polyline": "q_oqGzhjxPlAVJYmK{]sL}RuCoEKHgAmCuCcDaBgD_SmZ{BkEIi@u@u@M]RE\\h@Um@KHZb@Eq@q@}@XcBj@qAlEsGdFuFdC}GpBaB|@}B~AcBvGsRl@sM|@gElAgCJm@LaBBmDO_CP_Hw@oFt@wGWiCVmABoDlAeDh@k@zBm@zFj@rEiBrGCjCi@hCeAzEaFfBmDxC{Ir@oJjCaRhBkLrBuHtAcCvFmGPm@vCgCjHsFp@uAzCkDhFqH|EiEpFqI|CsD`DyG|EiMn@cApFcEhB}BtGeLfB}DvGeQhBaCfDs@lBmAVBpH}EzLoCnDWfFx@pBvApA^dBLfIa@lBnAd@x@PlB^|@fBp@~@[lBiBnDqF|@w@dFiAfOqAlKb@hHcAfEGxChAxBzAbGnBzBbBx@bBl@VpAQ~D_D|Aa@lCRjD]zAjAtEtPZtFt@rBxAdBl@zB?nEPdBl@lAxBvB[`@CdA]\\lAhBp@`LAzDe@zAGfFTx@K`DNp[E~vA@pEj@dHN`I@v\\XLArFl@xBXpEb@jBH~Av@`B`CbDhBtBbAvCd@`FQ`AArC^zFbCbKRhB`B~Cz@|@~BbPEdEm@nAgCbC}@tDVfKCpEdBpAbDb@vBdAj@~Bd@|Hf@zC~@|ChBdClBbChArCz@zDh@nE|@z@jCc@p@b@j@dAz@`E]xDNxBQhDc@j@yCRyAvC_CjL_CtHIxGh@fC^lE_@`EZlBCtB}@bHD`D^hDMlAmD~BYt@yBfBmAnBiH~@sCIiAdAcNV}AnBeAhDaAJgAt@`DxIt@jDtAtHJjEG`I[hGu@nGkAnG_C~GeCnDeExBaABgCcBcFiAmEeCgCkBcCaD}A_AuGeAgG{D}CgAuHeAc@g@SgEOYy@E_Bb@yBxAo@i@}ANo@fDw@`AaBZyBhCgFNo@z@CtBOfCo@vDkCbG_@dBEvCS`A\\tCM~EVvEe@|EcAzBoBPgGuBuDm@uBVkDxBqCXaKa@sI{AwBw@cDsBsHiIuEeDwBuCuAgGEmD{AoG]oCs@wDjAgFNmBl@eClB}FtBgEGQ}DBwAeAaCo@k@TaAx@cA`OkBnPc@|B]j@mAXiDQuE~@cJXuChAqA_@_@m@YqAFyDQaAy@}@qCFaAk@eAmBEeBZuAlH{GjA_@hB?bAg@RiC}@{B_B_BuAk@qH}AiEFwHzBaC?aA}@QwBq@SFmB~AoCJyBI_JByCHeCIsa@DqFPoA_@MK^mABoRGYeQwB]o@w@{Dm@}TB",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97417552396655,
            -93.28285125084221
        ],
        "end_latlng": [
            44.97177335433662,
            -93.28814232721925
        ],
        "average_speed": 7.794,
        "max_speed": 14.914,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 277.7,
        "elev_low": 225,
        "upload_id": 13434916921,
        "upload_id_str": "13434916921",
        "external_id": "stripped_31281392-B6C8-4DFF-8DAA-849E113E0B8A-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 43,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 192.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "30 Miles!",
        "distance": 49230,
        "moving_time": 6258,
        "elapsed_time": 6519,
        "total_elevation_gain": 143,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12625227628,
        "start_date": "2024-10-10T21:11:20Z",
        "start_date_local": "2024-10-10T16:11:20Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 79,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12625227628",
            "summary_polyline": "__oqGzhjxPn@Hl@nAx@fDxDfKdExAhAFVm@z@x@xGv@^d@H|DvId@d@pAv@Aj@`AVtG?xeAXb@jDNJhFzKZJnBr@Nb@sAhD_EzGmFnAX`NfK|Ed@|AiBfBiHjDs@|KhHdGnI~@hDvCeAvDlBrDC~CrB~J{CvN_HtCg@v[tArE`BfE`DtFpNbB`MWdKiDjIa@hBWpEf@rDOhEPzEmAbHmBhAgOiDsGhCsEj@}MiA{F_B}EsCeQ_Q{@mAwAcGDeCeDoRdBkJ|FsOh@WnBxAzAOhXoLxCk@`\\vAxDxAzEnDfFpM~AxIzAfBbDAlAa@~AsBtAKp@{EjCc@\\d@fFyB|BFr@s@a@_Sv@wJtB_MfH{OdEkBzLFvDz@`X|L`EbDxAdCtClJ|AvIVhNiCnWwCxIuB|CeFvCiBMuBwAcFeAyCaBsJwIsGmAcIsEsMkDFmD~@kAD_BWU[yFGoIzCwSnBaHhEiI|BmBlBa@zH?hFt@`XrL`HrFhD`JnCdQBbIoAdQcA|F{CvImBrCkEhC}@FsKoDeDcBcKeJiGcA{IaFeL}BE_Ez@mB[kKH{K`DgSzGkO~AyApCc@fI@~Ex@|WnLrG~EjCcAnByFpAq@hMI|AqAtDDf@jAz@VhIQhC_HlCsCp@qB]gKdA{UDgG]wANyBrAsGx@eH\\eGbDoBt@gBCiGf@gEEmBaByEmBYwDeByCsMmF}HgAgFkAoMy@w@{I}C]sQx@{CrCmCfA{CoBiRyD{G_D_Nc@}GRwEg@yEkEqIqCoCgAwFQsEk@qBBgF`@eMWoG\\kDqA{N`Ce@d@lI~C|D`EdB~D{@z@fA`FdChBlHfC`EdE|BdGvNpKrCfAjAdCZfCxCrFwApAeChAgHAqBjB}Fo@eMaCkJaEmG}BiB_JyDuEiG[qDm@uAcHyDkOcEmEoDyAPaCeAeBl@sA|BaCxFgBbJg@k@AgCwBiB]{GhAaIDcGCqzAc@eFAwHu@kJJw@}EcHUmBVsAMqCgDkGc@gH{FkRiAg@yHLoCbAmEtC{CoDuImDsG{CmQhAcIc@yUzCkInKyAh@{AeAaBmFsBoAiLZyDwBgFs@qL~AwDfAgLfHmDj@{@z@_I~RkDdH_HzKyHbH{EfMiEtIeJpMyG`HaIxKuRnQuEbG}A~DeApF}CrScCbUaCdHcCnE{HpGaDt@{GD{EhBkFo@qDtB_AzCUxKm@nGl@fGEfSwC|I{@xO_GvPcDtFuBdBgCfHqLvN_BrFiC|@wCjE_LpFaAfB_@|CwCjBq@lAmBfHc@bD|@~BNnCg@bBcBbAoCC}CjC",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.974083323031664,
            -93.28285527415574
        ],
        "end_latlng": [
            44.99225964769721,
            -93.27516010031104
        ],
        "average_speed": 7.867,
        "max_speed": 16.554,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 280.6,
        "elev_low": 225,
        "upload_id": 13460319969,
        "upload_id_str": "13460319969",
        "external_id": "stripped_150AB54F-AF32-4D63-9A91-BD74C07F9E9F-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 23,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 133.8,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Century",
        "distance": 161386,
        "moving_time": 22837,
        "elapsed_time": 24419,
        "total_elevation_gain": 622,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12640834070,
        "start_date": "2024-10-12T16:42:04Z",
        "start_date_local": "2024-10-12T11:42:04Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 88,
        "kudos_count": 2,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12640834070",
            "summary_polyline": "s_oqG`ijxPbNx^h]vAxArT~UHJd`AmB`I`P{NtVhMjJmMnZvYqBxy@fBdY|LvWvDN|HhYxIlhA~rBhtIfDf`@oLv@qjBmx@uAiEwKy@s]}UuIcNkHyb@}F_Li|@_{H]gh@qJum@fDk@uLe]mF}]oOuXpJzPpCaCwA}GbDyH^e^jDmB\\_KlHh@bf@vZZ~HbKO|f@xVdS`A|@bl@hHhBf\\qNnc@rDlHnHlGhXeFpXyAtc@ep@g@a_@aU|\\bUdq@`C|CqDKe_@vFwW|MkGlBuFtN{Bf@m_@rLo^fS{@n_@zPhIpP`Bba@_K|_@kHtCo|@aa@dCel@bMiZdUNz_@lS`JkJzb@IxIkP`@mp@bDqXzEiFZmP{B_GiE]wLiXmDqVgKmEU}QxFaP}Lkf@cAsV_M_Ws@{z@lLo_@fJo@j^zO`IdPrPjKfG`^sEzUsHhC}ToLgVwa@qT}FiHuOk@cdDx]q_@yHaOjK}FfA_GqB{D{R~I~BjJnCMnIvNhLcOlRwl@`UoNnd@aKpNie@~Bek@dEcHhDPlFjRvWvTlFyIpg@}KhRhm@rPpObGjTvIlLqJwMmDcQ{RuRwNek@}JiN}I`@eIrRqKrF_CrHeXeTeH_RkDjTpIrEnn@}sA_Ve]eHo^?_R}eAutAy]au@y^yNoYeVso@}aA_Pik@sXsWqb@uu@cMwDmDdDcGcIpG}JtGn@kFqg@dAsIal@de@pCtZsA~UwD`HdTf[{@tsPeGcVSv]kn@dKyNlTwSjj@qR|P}]`m@pKhWYbLCeMsMeSc^fr@sHtn@qGjC}P{D~K{@zEtc@pOhA_@sN`FmLxMw}@lx@u_AbLwWva@or@lSaKdQaDtYtCzHnJpLqLpSqCl]k@jWrNjTyEvT`u@tB`dFjNpZl@pUbM`h@cG|OYrg@pKr@cJmVnKnE|AjPlMj]bGdA~AfFYdOyGtE{FlUPbv@sKdKg^xCoH~I~GrWVxMuB`WmHdQmFpCwKwD_PeMk_@_Lc@aGoL|AsBtFqNbFmFdW?p]qCfFwo@{Am[{TeKgc@rJo]gNaAl@ptAtHfSpIbFdHtW`KbkAprBpsI`E~\\kGpD{JuD?gq@eIu]fEqA}`Bo_HcKykAmGsUqOwOeD{PvByfBKmaIqHy_@m@gXseCvwA}JkGeh@h`BwLcUaEh@gZxZcDxZot@pRwMoCi@jTsrAxBqu@rIw`@vSqAlLyPXuD`SmUpf@DbfEeIIR{u@[vG",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.974186420440674,
            -93.28288368880749
        ],
        "end_latlng": [
            45.038512498140335,
            -93.3220486342907
        ],
        "average_speed": 7.067,
        "max_speed": 16.145,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 290.3,
        "elev_low": 213.6,
        "upload_id": 13477194728,
        "upload_id_str": "13477194728",
        "external_id": "stripped_B17B541B-FD01-48E5-9CEB-DB72BC7E76A3-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 30,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 148.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "20mi avg/speed PR",
        "distance": 32425.2,
        "moving_time": 3957,
        "elapsed_time": 4103,
        "total_elevation_gain": 140.7,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 10,
        "id": 12665005262,
        "start_date": "2024-10-15T21:17:20Z",
        "start_date_local": "2024-10-15T16:17:20Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 61,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12665005262",
            "summary_polyline": "wrmqGtkkxPxBv@MvFBlHNdAdDBb@Vl@Y|LD\\VCv`AAViBnCKdAR|@l@D\\kAfEcFtEgE|@Mr@LfNtKhB`@lBDp@[f@u@hBuHz@o@tAWpBr@bIhFfC`EvCnD|@|CjAaAn@GtEzBhDMdB`Bn@LpAIzCgBvE}AjHqDxCmAjCe@xGFzRrApE`BvErDz@`Bb@tB|BlFbAbE`@zCxAlBlDKnA_@zAiBzAYXo@ZcCz@kArAAb@j@Za@rD}AnBLp@a@Ns@Y_HA_JZuEfAkIfAmFhBiFjDaHbAiA~@e@|A[bFErGd@fYzL~BvAzCnCzC}@jBaFd@o@v@U`MKr@_A`@K`BV`BUV~@p@b@`IOp@a@pB}FrCwCn@uBDuA[mDGqDl@{ITeKF}HCgB|@mEdAyIDwDN}@|@sAjBq@bAaCBkBOcCb@wEC{@]gBeBwDu@MeBZm@e@c@eAiAuFgBsEkFgIkAcFs@gK[wAy@q@}FsAsAkABkB_@yHDmD`AgDxBoBz@}AHkAKsBiB}OmDqFkCeLq@}ITwEu@_GmBwDi@c@WcAcD}CW}C_@sAYyEg@kBAeF\\{BNkDCgFSaEZuDe@qACoD_@{@GsCUgAH}@Ow@?}GSyEPcGOO?c@~@}FFaFGuyAEkE]eCAuGi@cJFyAaBkDaAm@e@}@UqAD{CSoBm@uBsBqC]uBGkDgEeOo@}A}@k@}JTcCnAiBhBeALu@[q@gBcAq@mKiFwDqA_F@{I|@}J]qLdAgGjAaAl@uFbIwAdAm@FiAw@aA}Dm@eAy@m@wASaE^wDAsEcCyFk@qOnCaC|@mJfGaC\\{@h@mBjC{ChHsBjGoCxFwGvK{A`ByDnCo@~@_FdMoErI_L`P{DrD}IvLiS~QiEdGsAfDeAbF_EdXmA|Mq@`EkE|J}E~EyCvA{Cn@eGB{ElBkCo@}BB}Ap@w@bAaAlCE~COhAFRMNJpCq@rGIATvAM\\d@pHPvFMfG{A|Co@lCcAfP_CbGmCzI{AvAcAhCgBrAsCrHwDxDoF|H_ArDa@`AeCv@_DxEsI~Co@l@{AnCChAUz@gBlAkAtAsCxI[dCp@xAZzA@zAUhAg@z@e@X{C@eBz@rBs@fCBnAqAZsA@eASyAy@wBBiAhC{Iz@_BpCwBV{@F_Bz@sArAyAdJkDnCiEtCyAb@uCb@{@xGgJhCiChDwIzAaAhAiCvA_BnGoR`AePlB}E",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.96882317587733,
            -93.28816713765264
        ],
        "end_latlng": [
            44.97758746147156,
            -93.24756402522326
        ],
        "average_speed": 8.194,
        "max_speed": 14.094,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 277.7,
        "elev_low": 225,
        "upload_id": 13503170190,
        "upload_id_str": "13503170190",
        "external_id": "stripped_1E8FFE34-6EE3-49DD-BC82-14916E19B31F-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 22,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 156.6,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Light 30",
        "distance": 48905.7,
        "moving_time": 6475,
        "elapsed_time": 6811,
        "total_elevation_gain": 122.9,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12673371503,
        "start_date": "2024-10-16T21:05:59Z",
        "start_date_local": "2024-10-16T16:05:59Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 39,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12673371503",
            "summary_polyline": "qvnqGzxjxPvCjGN|AAxEe@l_@o@bDaFxEx@Dp@dB@pAbMrUjBrHvDnVnBfHrItT_@MyB^Il@dBhHb@xGpBnGxBzRKv\\b@fIDeApGa@zEZnErCrEBdAtAjAbGjBdBzFgAdDJ|BeAn@ZF|AnFl@|BsBdBiFtB{Cx@wD`AyQMsDo@cHdBkGmAcIcDaDSiOaKb@eEfAwAmBAeFa@{AyEe@iBgC?eCp@{AbHgGfFkAT{B_AaCuBcBiJyBkFJoHtBoBA_Aw@S{AN}AjL{LhBElM~JjE`AtBu@hCaJlDm@bKjG`HhJdAlDtCiArDvBtCS`ExBh_@{Nx[lB~Cz@tF`EfFnMbBvIrArBlBHjCu@fEeCxAeFfBUd@l@jE_C~BHl@i@QqStB}R~CqKjDaHlBiB~Ii@dIz@fXxLfG|EbCw@|B_GrAu@~LMbBmA|D@`@fAp@VtIKjBmFzEaHLgCg@wHf@sF`@_\\lB{L`@qIv@wA~BeAr@}AZkPaCyGgEU}EyOwEaH{AmGuAyMwGsBmB{AWyPhAaEhD_EHiEaBsNwD_HcDwN]uGRmEm@oFqDcHiDsDuBcPCcFl@eGU_MXgEa@gAGeE}@yGH}Jc@uNhAyIGoaBeAo]o@]Kv@f@rAh@jM_@zIA`[BrwA\\bVjC_@f@nIvCvD|CjApFi@`AvAxEfCnBrHbCxDdEfC~GzMxPxG`CrCvFiArAwBpAkHBeCdB_Gg@uMgA{FqCuFsCsD_LkF_FcGk@qEk@aAqHoEaN_DeF}DqAVqAiAcAA}B`BiFhNqA`OyBn@t@rFf@dG]nDTrNk@xEDxFbAlIv@`F|EjGtBzEh@|EW~D`@~GlDzNjDtFxAlNElF}CnDcAhETzQlCnBdFdAdBfPbAhD~F`J~AfFbArGfAd@lDJbBlH[jL{@z@gCPqAhCeGvUKdHdAnIYhEZxBIpC_AtHb@`J{DbCyEdGyGfAiDIkA`AcNVeApAwAfEiClAtDjKtBhLB|PuBvSeBfGkDfGiEpCyAFqCeBqFqAaHoEoFkFsGiAmLeG{HkAc@i@g@cFmK~Ao@h@mAjEgBd@_BlBaG^m@fA?dEo@bEwDjJ]zEd@hDFlNo@jEkAfBiCEwJqC}GrB_Dd@sQgAwJsDiPcOaRh@yCpBTrA[vDkCl@uC}@j@jMcA`Ru@|CgCxDkB|FqBrAoDYeAo@CsAq@ImB`AqIbAcBMoAqAmAmGkAuAuFQeEoCgNNK}d@sBkRmBoGo@sH_BiHbC_A`@P{IkUcBqGgAyHAoE{@}AyBkJgCeGgJgPI_Bk@mA`BwDtAy@^wAb@{W",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97420326806605,
            -93.28325048089027
        ],
        "end_latlng": [
            44.97185650281608,
            -93.28667180612683
        ],
        "average_speed": 7.553,
        "max_speed": 13.478,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 271,
        "elev_low": 248.5,
        "upload_id": 13512083506,
        "upload_id_str": "13512083506",
        "external_id": "stripped_C664AD1B-3109-4E5C-AA03-745F16115B0E-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 21,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 159.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Run!",
        "distance": 16093.4,
        "moving_time": 8280,
        "elapsed_time": 8480,
        "total_elevation_gain": 0,
        "type": "Run",
        "sport_type": "Run",
        "workout_type": 0,
        "id": 12696756412,
        "start_date": "2024-10-20T00:24:26Z",
        "start_date_local": "2024-10-19T19:24:26Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12696756412",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": true,
        "visibility": "only_me",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 3.3528,
        "max_speed": 2.93,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 348,
        "elev_low": 347.9,
        "upload_id": 13537199713,
        "upload_id_str": "13537199713",
        "external_id": "stripped_AFF2CC9C-4EAD-4D43-B20D-7ED52310746C-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 167.3,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Family Ride",
        "distance": 35479.7,
        "moving_time": 4596,
        "elapsed_time": 4726,
        "total_elevation_gain": 130.7,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12704812189,
        "start_date": "2024-10-20T20:26:05Z",
        "start_date_local": "2024-10-20T15:26:05Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 61,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12704812189",
            "summary_polyline": "eaoqGj}ixPgCkHiA}EyAyDoF_JaBcBq@uAMBAY_HgLuAsA_CoEsFkHcJ}NkEiICQNC^f@]o@Lt@H?Cg@q@}@VgBh@sA`HuJtBmBtC}HxBgBlAoCnAqApGwQ|@uOv@gDfAsBXsALiEQ}DNyGy@oFv@eGQkCZoBC{ClAaDlBuAn@GbBCrCn@tFkBrF?fDm@dCqA~D{DjBmD~C_JhBeRbDoTdAsFbBcFrAwBdH{H~NqMhHkKhFkFjFcI~D}EpDqHdFwMpGkFdGmJfEmIrGaQtBqCzDaAvLiHdQcDjFr@zDzBfCFjIWhB`BpAtExAp@bAYzBwBrDqFv@k@vCy@dP_BlLXbI_A`E?pC`AlLnFlAx@~@rBp@Nv@IjDqCrBu@jCPtD]|@^j@z@jEdPTfF|@fCtAtAl@jCJlAKnCV`B^t@bC~BOZF`Bb@rAh@fID`Ha@dDE|LAf^FdiADjOf@dHP|MJhf@x@xEhAbDrCnD|A`AvAfCz@xGQ~E`@|G`DbNbDhF`@`BlA|LFxCQhAc@v@oCbCy@pDP~ICxFrD|BhCNrA~@bBjPtAfEzAfBnBtC`AbClAzEd@hE~@h@tB_@`A^l@dAz@~E[`CJ`DYtDuAt@sAGaBjCwBpKiCjIM~GhAvI[nEZ`BEhCs@tDYfDh@pIsDtBc@dAw@b@eApA}@tA{Cn@kHPmA`AcKB}AX}@`AwAlEYXm@EeAz@rBdFbB`G~A|JH|H_@pJqAlL_B|GyArDqBrCmDxBmA^}@UgBqAsFqAiCuAeE{CwBsCqAu@aHsA_GoD}DuAiHkA_@o@?uAm@eCaA?sEbCc@k@kBXc@x@_@bCWd@mB^eBnBoCd@{AKw@fAChFq@`E}BzEq@zBIdDQbAj@rCKvFZhEg@fEqAnCoAZsMiDmBPcF`C{I?cHq@iDs@oGuC{JaKmDgCqBcCiByH?{CuB{Ku@}CZsCr@_Bj@yExB{GvB}EiERiByAmBg@aAb@AVt@f@K|DRhAQbBaBvo@B|Fs@f@wCbBwDc@oAxCWdBC|Cf@fCNhEy@xPw@pD}@vBiAvAaBdFsBfBwDYgAa@]s@_BMw@\\uCIkDhAgBKsA}AoAqGmAsAyECmFuCuEI{Fb@MaDL}JO_C@gPaA_Hg@}G_CqI]_CCeCgBaITa@v@Lr@m@`@d@DMoCgIoEiKiBkHaByL]a@{@uGmAeFmCmGqIcOGyAaAqCz@kAEe@}DyD{AkDmAaAsEmKOo@EcLlAFb@U",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.974165968596935,
            -93.28293196856976
        ],
        "end_latlng": [
            44.97364821843803,
            -93.28813696280122
        ],
        "average_speed": 7.72,
        "max_speed": 14.988,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 268,
        "elev_low": 224.4,
        "upload_id": 13545871863,
        "upload_id_str": "13545871863",
        "external_id": "stripped_19681289-1A8F-4FD8-8B87-62420A6F6A29-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 29,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 103.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Super Tiring",
        "distance": 21244.9,
        "moving_time": 2787,
        "elapsed_time": 2842,
        "total_elevation_gain": 93.9,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12712582376,
        "start_date": "2024-10-21T22:08:45Z",
        "start_date_local": "2024-10-21T17:08:45Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 2,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12712582376",
            "summary_polyline": "uxnqGjzjxP`@Id@H@^LTVhAOp@@dALXVFLZA~@JrAJBDRj@CfEPfPBzCVf@XJRCTJV~AVBKRPK?JND`@C|BPlDEnA?lCFTbBI|ALdBKlE@`FPB\\GRAz@JpLGlEAxZFlMGv@eA~@_@|@GxAF^JJn@BDc@Re@tEyFjEsDl@M`@Bl@X`GbFjExCrBd@lBBz@c@^s@Vy@f@yCj@aBh@c@nAW|@JnAn@tDnClAb@z@r@zBjDxA`BbAvAVn@b@nB\\Cn@y@x@E`Bn@jBjAfASnAEt@^t@`A|@Tt@ChDeBpGyBhBgADWfA_@T[|BaAfAk@`CM|JTvDd@`J^jANzAj@tBtAlApAbAn@bAlB`@`BxBlFv@`Dp@lEvAfBr@Af@Lx@IhBm@jAwAlBc@Vg@^qCr@y@vAKRb@LDR[pDeBfAIr@Xt@k@Je@GM?mAQcCEwD?mEf@gIzA{J`AsDr@qBxDaI|AcBlAi@|AQhID|BZlCv@vJtEfHrCvCbBfEvDnB|Ef@`BdAlEnApHF`C@hIe@`Iy@fHg@lCoAzEgAvCu@rAoAxAeFnCqA]uAcAo@UkCq@q@CoBmAm@SqDkCyAwB}@y@wAu@iA[aBIyA_@uFiDyAq@oBi@{@Cu@e@qDU[[GSAyAQu@Dk@Yg@eA@mBp@oAl@a@f@CYUYsAFQJMd@k@hASvA_@d@aB\\qBxBUAaB`@s@O_ADm@fAB|Cm@tEc@nBSd@_@\\e@v@s@bBMl@GjDS~@j@vC?pBOpBR|C?vAMhB]fBYx@o@|@k@TqAM_Bc@wCkA}Aa@oAKkBRyBpAoAd@oBRwGKkHy@wBe@_D_AcC_B}CmCeE_FqFiEkAaBe@wCq@sBGm@@uBaAwE]aA[sCm@uBCm@VcCr@gBNeBTw@?URgApB}FpBqECSyDRgBqAaBe@i@@]XWf@]D?l@eAtMw@lGa@tEm@vDe@z@iAZsDMuGbAmGNoDnAk@Go@i@Wg@Os@Cy@HgCQmA[c@c@UeCHgAi@i@s@]aACmBXcAh@s@lGyFfB]tA?h@[Z{@@cAIq@{@_BiAgAyHcCuBOoELuFjBy@HiBE]Mc@k@UgA@q@m@SAq@@c@Ns@P_@x@{@JUHo@GmAB_CDSEmFF_CGgAD[CePFwIEkGa@S{TGEcA?gVQ_@iBW",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97408944182098,
            -93.28288913704455
        ],
        "end_latlng": [
            44.96882543899119,
            -93.28744352795184
        ],
        "average_speed": 7.623,
        "max_speed": 12.526,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 277.8,
        "elev_low": 250.5,
        "upload_id": 13554250636,
        "upload_id_str": "13554250636",
        "external_id": "stripped_11905CBC-7486-44CD-B9EA-92CB3CA209D9-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 111.3,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Nice One",
        "distance": 26320.4,
        "moving_time": 3343,
        "elapsed_time": 3432,
        "total_elevation_gain": 85.6,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12720894756,
        "start_date": "2024-10-22T21:13:16Z",
        "start_date_local": "2024-10-22T16:13:16Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 34,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12720894756",
            "summary_polyline": "_boqG|}ixPOqAc@oBwA{DuA{EFS_AmBy@}AgAiAwA{Ca@]Ok@i@o@WKm@uAyCqE@QK?aC_EsA}AoAiBa@}@_B_C]SMe@{C_EkA}BqFqIm@iAMw@mA_B]aAs@y@ROTp@HG_@o@Jp@JD?Yu@kABu@b@{Ab@u@xGiJdCcChAcDbA}Bf@o@fAu@~@eC`BgBzDaMp@kAb@{A^yFTmGv@aDlAwBZgCFoCOyDN}Gq@aDE}Al@sEDwAQsAXkA@{D\\}AxA{B~Ao@rB?`Cp@`AK`B}@tAa@xFCnDm@nCsAh@w@pAaAx@cAxBeEzCqJxAyObEyX~@mElAaDzA_CnC}C`N_MvB}Bl@_@xHyKhGmGzDmGhEoFfDcHvFmNbCgBHd@sAhAMV?\\nBxEnAlEjAnF`@`Cp@pGLjDDlIuAt}@EdKJrA?hBZnAh@lAz@`A|AlAy@pB}@|AzClMJdAh@\\Pr@Cf@Lp@FvHA|IbCrFnAdEv@jER|BHvBAxRJ|DIrC@lRKvAA|G?bAHPGnAF`GKvAGhET|SK~KJ|JGr`@H|NJhDELGjHA~SF~FELGnEHf@H~DKdGFt@GfIDxGI~BFfDAzGGdGPbJGvJPxGKfBC|FYrHMjH_@EO_@WKDUh@Yz@IdBp@tAfAdDAdAj@d@r@fAPvAa@dBgAlHcCvGkDp@KlAo@pBWjDGpGN|OfAlD~A`C~Bf@Tv@|@t@dBRpAjBlEl@rBfA`HJfC?hEc@lDi@vBYp@yA~B]|@Kn@EfDO|@b@fBH`AUxER~DCpA[fCcAfCc@Zy@HwBe@gB_AeBe@_Da@kBVuAbAqAh@mC\\oGMaHu@{GkBiCaBaCoBqEkFeE{C}A}Ak@iAo@qDg@wAEq@BmBoB_IO}Ag@eBKgAZeCr@gBh@aEJe@dBiF~AyDf@{@?WON]KwCHsAcAcCo@m@Pe@r@W?InCm@pHmAtJ_@`Ek@pDg@t@gAZqBO}AFcHbAuFDeDjAw@Ye@k@YsADuDOaAe@o@_@Q_CF{@]i@k@g@gAIk@@eAP_A`@u@rF_FbBw@vBCp@]^{@@aAOaAm@mAcAmA]SuI}B_GBkHvB}B@k@QW[Su@GuAs@eAJ}@dA{AXs@B_CLaA?qLUOg@T_HYEM@aEMa@sDIIKHcAGSDmBMYeBGCMeADMUFcDAkRESH{EA}J?uBOaAmBWSUG[wBWm@[iK@",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.974081395193934,
            -93.28295954503119
        ],
        "end_latlng": [
            44.97176648117602,
            -93.28820284456015
        ],
        "average_speed": 7.873,
        "max_speed": 14.408,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 280.3,
        "elev_low": 224.4,
        "upload_id": 13563126746,
        "upload_id_str": "13563126746",
        "external_id": "stripped_7631F571-730B-432A-86DE-4E4D208F62EB-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 9,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        // "average_watts": 129.9,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Oops, Accidental Upload",
        "distance": 3.3,
        "moving_time": 20,
        "elapsed_time": 27,
        "total_elevation_gain": 0,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 12,
        "id": 12727545298,
        "start_date": "2024-10-23T17:39:25Z",
        "start_date_local": "2024-10-23T12:39:25Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 0,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12727545298",
            "summary_polyline": "",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": true,
        "visibility": "only_me",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [],
        "end_latlng": [],
        "average_speed": 0.163,
        "max_speed": 1.087,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 261.2,
        "elev_low": 261.2,
        "upload_id": 13570258236,
        "upload_id_str": "13570258236",
        "external_id": "stripped_E060067F-925E-488A-A786-81BFF6B9A0AB-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 140.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "15 Miles",
        "distance": 26610.6,
        "moving_time": 3499,
        "elapsed_time": 3551,
        "total_elevation_gain": 104.5,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12729331893,
        "start_date": "2024-10-23T21:23:38Z",
        "start_date_local": "2024-10-23T16:23:38Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 21,
        "kudos_count": 1,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12729331893",
            "summary_polyline": "cboqGn}ixPk@eBN]AWyA}DI{@mByFkBeDeA{AaAeBMe@i@k@sBkDs@w@oBmD}CwEkAqAcCgEmDiF_@y@sIoMsAiB_@eAmAeCw@eAAOPANj@J?Yu@AZZZMw@k@o@V}Ap@cBdGqInCkCb@y@|BeGhByA|@cCdBiBdDmKjBaF\\qFAwANo@NkCr@iDrAcCR{ADmCKgEJaHGq@g@iBI}Ax@eGWaDZqA?_DZyAvAuBtBq@fB?vAd@`AFj@KxAw@bBg@~FBvCm@jCoA|@eAdCaCv@qA|AmDtBgHdBaQrDqVjAoFjA_D|@aBdBwBxA_B|D}DjFmExCcDp@]r@y@fEeHpHqH~EyHvDuExDcIbB{ErByEnAuAz@o@L@Hf@yAlAMj@rBnEJt@l@~AfAvEhA|Gd@dFHjC@vOKtBa@z\\IdBIvGF|@OfDKrK@jCHtCZ`Bh@hAbAhAb@^d@LNTiAfCs@jA|ClMHv@Gx@_@j@eC`@wFnBW\\On@LfAJFt@nBTx@nFnAdAtAhAt@Nr@^DX\\xBnFv@fCfAhF?l@^jEAzSHtQEzBH`CUbDEhI?XHJGPBhJGlEH`\\KpFLbCGNJhEGzLDbQPYO~@EzBFZAlFFnFMln@R`GIl@GtCDdB@zPE|FJnFO~HJvNHlAIpHFvFCjEo@|TaAu@h@o@nADjAb@bBjAtCW`Ah@|@|@hAPx@UjDkBnFgBdG{ClAYfAo@vBYbGE~TtAxD|AjC`C|@f@`AfBf@rBpBrEj@rBfAzGJxA?`G_@zCm@fCcAzAwAvDIvDMx@^xAF|@A`CKnBXrFi@fDUz@k@bAWVm@LyB_@}BgAuBk@sC[yAToC`B}Bh@{HG{Fk@iDo@qC_AkC}AyCkCcEyEiEaDuAuAs@mA_@gCy@oCC{Cy@wD[_Aa@oDq@sBAm@V_Cr@gBLsAj@yCxAsEhCcGCO_BEm@L{@MmBiAeB_@q@f@Uf@[DQ~EmB`Q_@jEk@pDo@|@o@NaEIyEv@{CTsD@sDjAcA]_@i@[mAH{DWoAs@o@gCHmAm@aAkBKiADs@Lm@Va@pGaGvAi@vBCd@W`@w@Dy@I_A_AoBuAqAuHwB{AMwDF}@LcExAmARuBIe@YU[Kg@EqA]q@QEGWZuAjAsALi@FgLC}c@Q][GeMEk@@MNo@OqBDM[g@VoCA{Bl@QSqBeDW{A@yBNy@VkD\\{BpEwF^yAFeA",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.97406161390245,
            -93.28289802186191
        ],
        "end_latlng": [
            44.96884144842625,
            -93.28741452656686
        ],
        "average_speed": 7.605,
        "max_speed": 16.092,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 280.9,
        "elev_low": 224.4,
        "upload_id": 13572147784,
        "upload_id_str": "13572147784",
        "external_id": "stripped_6F744748-DFAA-495A-88B5-6BBD63FC83D8-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 5,
        "total_photo_count": 0,
        "has_kudoed": false
    },
    {
        "resource_state": 2,
        "average_watts": 142.2,
        "athlete": {
            "id": 137448695,
            "resource_state": 1
        },
        "name": "Rainy One!",
        "distance": 50351.7,
        "moving_time": 7196,
        "elapsed_time": 8513,
        "total_elevation_gain": 162.2,
        "type": "Ride",
        "sport_type": "Ride",
        "workout_type": 0,
        "id": 12737675660,
        "start_date": "2024-10-24T21:21:50Z",
        "start_date_local": "2024-10-24T16:21:50Z",
        "timezone": "(GMT-06:00) America/Chicago",
        "utc_offset": -18000,
        "location_city": null,
        "location_state": null,
        "location_country": "United States",
        "achievement_count": 0,
        "kudos_count": 2,
        "comment_count": 0,
        "athlete_count": 1,
        "photo_count": 0,
        "map": {
            "id": "a12737675660",
            "summary_polyline": "saoqGn~ixPy@cCPq@aG}P}l@}~@eFiJj@X{@gBdA_EjKiMlD}IlAw@zDcGvGyRx@yNdC}HZwDBoOy@uFn@sEIiEf@uHlAcCnBcA`Hf@xEiB`Lm@fCmAbE_EpAqBvD{KtBiStDoV~@kE`CuF`YuXtEeHpI_JzJmN~L{X|GuFvGmKfOk]jFiBnKwGhRmD~D`@hGnChKa@dCdBxAbFxAj@dEwCjFyGlTuCzKZtOcAlP`HdBhAvBdChEkCjCgAdIIbAd@nFxQl@bH|BjDj@|BXbIbDvDMhCh@hALdCXtJC`Ce@bBPzcCXbHjCSj@|InClDdDxAfFaAv@lAlFvC\\fCnAdD|BrDrBx@~A`BnGbM|G|C|ALrAzAxB`@bCpCnFqAnAsBpAmH@}BjAoCZwBm@oNeAaFaCaFmDmEsKaFaFaGa@uDk@yAiHmEcNcDuFeEgAXuAeAmAAqBtAkDdI_BpHo@~@WfIeB^v@fGBdD`@rA]`ETzMm@zFFrEj@|BVrEn@vEjDrDrDdHf@lFOvEb@xG`DdNhD`GnBtPYlD_DjDgAzDVfRrCnBbFdAjB|P|AjEnBvBrC~FpBnKp@~@hC[bAd@hBpH]nCGjHmAz@}AAkB~C_G~UGvGhA`Ia@lE^jEgAvJd@lHMt@_DnBqFxGqGdAgDIkA`AaNVgDbHeC`AbD`JhC`NDhP{A|OqC~KoDbGyDxB_APcDiBsFoAmHwEkFiFqGeAwIcFwKoB]m@QcEsAYaFbC]o@iAF_A~@{@zDkB\\}BxB_FRg@r@u@rK_EjKYvEd@xDMdETnFo@fFaA~AiA^{LsDcCLkEzByCTeMq@iGoAwFuCcSqRoB}H?mCmDmQfC{M~EeMpBlAtAElU_LjEgAj[dAtGhBhEdDxA~BhE~MhAzHAvGeAbGeDpHWzEl@vDQhEP`Gm@hEeAnBsBJoLaDqBTwDrBqDTmFG{OmC{H}FkEgFmGiFgCaJAqCoDaRnCuM~AaF~BqF}DDcFwBeBjAcDl^sAjF{W|AuF|@}@qBBkEWoAs@q@mCDeAi@eAmBEkB\\wA~GoG`GuATeCs@iBqBqBaJ_C}FFaGlBeD?iAgBCoA^cAvHsI`DeB`OxKhFp@dByAjBsHxC}@lKbGxHfKt@zCKhDoCjYaArE}Aj@kU`AwDlAiA[o@cAUuHy@y@oE_@aA}AMeCt@iBlG{FxFkAXeCs@oB_CuBqJ_CcEFkHtBsC?gAeAI{BxFyHnF}DrAZlM`KbFh@`BkB~BkIsIuIiUQgJy@So^oOOSqFsDSQ_YmB]kF_BwWUW{CTCc@CCo@e@c@@wCy@qAoAE",
            "resource_state": 2
        },
        "trainer": false,
        "commute": false,
        "manual": false,
        "private": false,
        "visibility": "everyone",
        "flagged": false,
        "gear_id": null,
        "start_latlng": [
            44.974012,
            -93.283101
        ],
        "end_latlng": [
            44.974082,
            -93.282756
        ],
        "average_speed": 6.997,
        "max_speed": 13.78,
        "has_heartrate": false,
        "heartrate_opt_out": false,
        "display_hide_heartrate_option": false,
        "elev_high": 278.6,
        "elev_low": 225,
        "upload_id": 13581081210,
        "upload_id_str": "13581081210",
        "external_id": "stripped_B51FCFE6-51A5-416A-AFE0-15977360F21A-activity.fit",
        "from_accepted_tag": false,
        "pr_count": 0,
        "total_photo_count": 0,
        "has_kudoed": false
    }
]